CURSOR MAIN_UNIT IS
	(
	SELECT DISTINCT
		UNIT,
		CUSTOMER_TYPE
	FROM
		AUCUSTOM.XXAU_CUSTOMER_DETAILS@EBSTOHR T1
	WHERE 1=1
	AND AGENCY_ID = NVL(P_AGENCY_ID, AGENCY_ID)
	--       AND AGENCY_ID='6074637'
	 AND   (EXISTS (
		   SELECT 1
		   FROM AUCUSTOM.AU_CUSTOMER_SHIP_TO@EBSTOHR T2
		   WHERE 1=1
			 AND T2.AGENCY_ID = T1.AGENCY_ID
			 AND T2.CENTRE_NUMBER = T1.CENTRE_NUMBER
			 AND T2.ERP_SITE_USE_ID IS NULL
	--        AND T2.AGENCY_ID='6074637'
			  AND T2.AGENCY_ID = NVL(P_AGENCY_ID, T2.AGENCY_ID)
	   )
		OR NVL(PROCESS_FLAG, 'N') = 'N')
												   ---AND UNIT='110'
);
