CURSOR CREATE_CUST (
	P_UNIT      VARCHAR2,
	P_CUST_TYPE VARCHAR2
) IS
( SELECT DISTINCT
		CUSTOMER_NAME,
		UNIT,
		CUSTOMER_TYPE,
		CUSTOMER_CLASS                          CUSTOMER_CLASS_CODE,
		MOBILE_NO,
		CONTACT_PERSON,
		NVL(ACCOUNT_DESCRIPTION, CUSTOMER_NAME) ACCOUNT_DESCRIPTION,
		ABC_TYPE,
		OLD_PARTY_ID,
		OLD_CUSTOMER_ID,
		AGENCY_ID
	FROM
		AUCUSTOM.XXAU_CUSTOMER_DETAILS@EBSTOHR TT3
	WHERE 1=1
	   --     PROCESS_FLAG, 'N' = (
	--   TT3.ERP_SITE_USE_ID IS NULL
--        TT3.AGENCY_ID='6074637'
AND  (EXISTS (
   SELECT 1
   FROM AUCUSTOM.AU_CUSTOMER_SHIP_TO@EBSTOHR T2
   WHERE 1=1
	 AND T2.AGENCY_ID = TT3.AGENCY_ID
	 AND T2.CENTRE_NUMBER = TT3.CENTRE_NUMBER
	 AND T2.ERP_SITE_USE_ID IS NULL
--        AND T2.AGENCY_ID='6074637'
	AND T2.AGENCY_ID = NVL(P_AGENCY_ID, T2.AGENCY_ID)
)
OR NVL(PROCESS_FLAG, 'N') = 'N')

		AND CUSTOMER_TYPE = P_CUST_TYPE
	   AND UNIT = P_UNIT

	   -- AND T2.AGENCY_ID='9456'

);