CREATE TABLE APPS.XXAU_AR_TRNSP_RCPT_ERR
(
  CONC_RCPT_ID          NUMBER,
  COMPOSITE_RECEIPT_ID  NUMBER,
  STATUS                VARCHAR2(1 BYTE),
  ERROR_MESSAGE         VARCHAR2(4000 BYTE)
)
/