SELECT HCA.CUST_ACCOUNT_ID
, HCA.ACCOUNT_NUMBER
, HCA.ACCOUNT_NAME
, HZP.PARTY_ID
, HZP.PARTY_NAME
, HZP.PARTY_NUMBER
, HCASA.PARTY_SITE_ID
, HCASA.CUST_ACCT_SITE_ID
, HZPS.LOCATION_ID
, HZPS.PARTY_SITE_NUMBER
, HCSUA.SITE_USE_ID
, HCSUA.LOCATION
, HCSUA.SITE_USE_CODE
, HCSUA.STATUS
, HZL.ADDRESS1
, HZL.COUNTRY
, HZL.CITY
, HZL.POSTAL_CODE
, HZL.STATE
, HZL.COUNTY
, (SELECT EMAIL_ADDRESS 
    FROM HZ_CONTACT_POINTS 
    WHERE OWNER_TABLE_ID = HZPS.PARTY_SITE_ID 
    AND OWNER_TABLE_NAME = 'HZ_PARTY_SITES' 
    AND CONTACT_POINT_TYPE = 'EMAIL') SITE_CONTACT_EMAIL_ADDRESS
, (SELECT PHONE_NUMBER 
    FROM HZ_CONTACT_POINTS 
    WHERE OWNER_TABLE_ID = HZPS.PARTY_SITE_ID 
    AND OWNER_TABLE_NAME = 'HZ_PARTY_SITES' 
    AND CONTACT_POINT_TYPE = 'PHONE') SITE_CONTACT_PHONE
, (SELECT PHONE_NUMBER 
    FROM HZ_CONTACT_POINTS 
    WHERE OWNER_TABLE_ID = HZP.PARTY_ID 
    AND OWNER_TABLE_NAME = 'HZ_PARTIES' 
    AND CONTACT_POINT_TYPE = 'PHONE') PARTY_CONTACT_PHONE
, (SELECT EMAIL_ADDRESS 
    FROM HZ_CONTACT_POINTS 
    WHERE OWNER_TABLE_ID = HZP.PARTY_ID 
    AND OWNER_TABLE_NAME = 'HZ_PARTIES' 
    AND CONTACT_POINT_TYPE = 'EMAIL') PARTY_EMAIL_ADDRESS
FROM HZ_CUST_ACCOUNTS HCA
, HZ_PARTIES HZP
, HZ_CUST_ACCT_SITES_ALL HCASA
, HZ_PARTY_SITES HZPS
, HZ_CUST_SITE_USES_ALL HCSUA
, HZ_LOCATIONS HZL
WHERE 1=1
AND HZPS.LOCATION_ID = HZL.LOCATION_ID
AND HCASA.PARTY_SITE_ID = HZPS.PARTY_SITE_ID 
AND HCASA.CUST_ACCT_SITE_ID = HCSUA.CUST_ACCT_SITE_ID(+)
AND HCA.PARTY_ID = HZP.PARTY_ID 
AND HCA.CUST_ACCOUNT_ID = HCASA.CUST_ACCOUNT_ID
AND HCSUA.SITE_USE_CODE = 'SHIP_TO'
--AND HCA.CREATION_DATE > SYSDATE - 1
AND EXISTS (SELECT 1 
            FROM AU_CUSTOMER_SHIP_TO_TEST
            WHERE AGENCY_ID IN (SELECT AGENCY_ID 
                                FROM XXAU_AGENCY_APPROVAL_DTL_TEST
                                WHERE TRUNC(CREATION_DATE) >='01-OCT-2024'
                                AND APPROVE_REJECT = 'A'
                                AND AGREEMENT_FLAG = 'Y')
            AND ERP_CUSTOMER_ID = HCA.CUST_ACCOUNT_ID)