CREATE TABLE AU_CUSTOMER_MASTER_NEW_TEST
AS SELECT * FROM
AU_CUSTOMER_MASTER_NEW@EBSTOHR
WHERE AGENCY_ID  IN (SELECT AGENCY_ID 
                    FROM AUCUSTOM.XXAU_AGENCY_APPROVAL_DETIALS@EBSTOHR
                    WHERE TRUNC(CREATION_DATE) >='01-OCT-2024'
                    AND APPROVE_REJECT = 'A'
                    AND AGREEMENT_FLAG = 'Y')
AND ERP_CUSTOMER_NUMBER IS NULL;

CREATE TABLE AU_CUSTOMER_SHIP_TO_TEST AS
SELECT * FROM 
AU_CUSTOMER_SHIP_TO@EBSTOHR
WHERE AGENCY_ID IN (SELECT AGENCY_ID 
                    FROM AUCUSTOM.XXAU_AGENCY_APPROVAL_DETIALS@EBSTOHR
                    WHERE TRUNC(CREATION_DATE) >='01-OCT-2024'
                    AND APPROVE_REJECT = 'A'
                    AND AGREEMENT_FLAG = 'Y')
AND ERP_SITE_USE_ID IS NOT NULL
AND AGENCY_ID = 5939
;

CREATE TABLE XXAU_AGENCY_APPROVAL_DTL_TEST
AS SELECT *
FROM XXAU_AGENCY_APPROVAL_DETIALS@EBSTOHR;

CREATE TABLE XXAU_CUSTOMER_DETAILS_TEST
AS SELECT * 
FROM
AUCUSTOM.XXAU_CUSTOMER_DETAILS@EBSTOHR;