CREATE OR REPLACE PACKAGE XXAU_COMP_RCPT_CREATION_PKG
IS
	PROCEDURE PRAGMA_COMMIT(P_PROCESS_FLAG VARCHAR2,P_PROCESS_MESSAGE VARCHAR2,P_CONS_RCPT_NO NUMBER, P_COMPOSITE_RECEIPT_ID NUMBER );
	PROCEDURE ENTER_RECORDS;
	PROCEDURE VALIDATION_REQUIRED;
	PROCEDURE MAIN(P_ERRBUF OUT VARCHAR2, P_RETCODE OUT VARCHAR2);
END XXAU_COMP_RCPT_CREATION_PKG;