SELECT SUM(XLA_AE_L1.ACCOUNTED_CR) TOTAL
FROM AP_INVOICES_ALL AIA
, AP_INVOICE_LINES_ALL AILA
, AP_INVOICE_DISTRIBUTIONS_ALL AIDA
, AP_INVOICE_PAYMENTS_ALL AIPA
, AP_PAYMENT_SCHEDULES_ALL APSA
, AP_CHECKS_ALL ACA
, XLA_EVENTS XLA_E
, XLA_AE_HEADERS XLA_AE_H1
, XLA_AE_LINES XLA_AE_L1
--, GL_CODE_COMBINATIONS GCC1
WHERE 1=1
AND XLA_AE_H1.ACCOUNTING_DATE < TRUNC(SYSDATE,'MM')
AND XLA_AE_L1.ACCOUNTING_CLASS_CODE = 'ITEM EXPENSE'
AND XLA_AE_L1.ACCOUNTED_CR IS NOT NULL
AND XLA_AE_H1.AE_HEADER_ID=XLA_AE_L1.AE_HEADER_ID
AND XLA_E.ENTITY_ID = XLA_AE_H1.ENTITY_ID
AND AIDA.ACCOUNTING_EVENT_ID = XLA_E.EVENT_ID
AND AIPA.CHECK_ID = ACA.CHECK_ID(+)
AND AIA.INVOICE_ID = APSA.INVOICE_ID
AND AIA.INVOICE_ID = AIPA.INVOICE_ID(+)
AND AILA.LINE_NUMBER = AIDA.INVOICE_LINE_NUMBER
AND AIA.INVOICE_ID = AIDA.INVOICE_ID
AND AILA.ATTRIBUTE_CATEGORY = 'MPA'
AND AIA.INVOICE_ID = AILA.INVOICE_ID
AND AIA.INVOICE_NUM = '117'

SELECT --GCC2.*,
  OOD.ORGANIZATION_NAME
, GCC.SEGMENT1 UNIT_CODE
, GCC2.SEGMENT5 EXP_CODE
, GCC.SEGMENT5 PREPAID_CODE
, GCC.SEGMENT4 DEPT
, (SELECT DESCRIPTION
    FROM FND_FLEX_VALUES_VL
    WHERE FLEX_VALUE_SET_ID =(SELECT FLEX_VALUE_SET_ID
                FROM FND_FLEX_VALUE_SETS A
                WHERE FLEX_VALUE_SET_NAME =  'Type of Expense') --105..1201.211.207510...105; 112.9999.999.999.209185.9999.999.999.999.999
    AND FLEX_VALUE_MEANING = AILA.ATTRIBUTE1) EXPENSE_HEAD
, APS.SEGMENT1 AP_CODE
, APS.VENDOR_NAME PARTY_NAME
, AIA.INVOICE_NUM BILL_NUM
, UPPER(AILA.DESCRIPTION) L_DESCRIPTION
, TO_CHAR(AILA.DEF_ACCTG_START_DATE,'DD-Mon-RR') MPA_FROM_DATE
, TO_CHAR(AILA.DEF_ACCTG_END_DATE,'DD-Mon-RR') MPA_TO_DATE
, AILA.AMOUNT ACTUAL_AMT
, NULL PENDING_START_DATE
, TO_CHAR(AILA.DEF_ACCTG_END_DATE,'DD-Mon-RR') PENDING_END_DATE
,  TRUNC(TO_DATE(AILA.DEF_ACCTG_END_DATE,'DD/MM/RRRR')-TO_DATE(AILA.DEF_ACCTG_START_DATE,'DD/MM/RRRR'))+1 TOTAL_POLICY_DAYS
, (SELECT SUM(XLA_AE_L1.ACCOUNTED_CR) TOTAL
	FROM XLA_EVENTS XLA_E
	, XLA_AE_HEADERS XLA_AE_H1
	, XLA_AE_LINES XLA_AE_L1
	WHERE 1=1
	AND XLA_AE_H1.ACCOUNTING_DATE < TRUNC(SYSDATE,'MM')
	AND XLA_AE_L1.ACCOUNTING_CLASS_CODE = 'ITEM EXPENSE'
	AND XLA_AE_L1.ACCOUNTED_CR IS NOT NULL
	AND XLA_AE_H1.AE_HEADER_ID=XLA_AE_L1.AE_HEADER_ID
	AND XLA_E.ENTITY_ID = XLA_AE_H1.ENTITY_ID
	AND AIDA.ACCOUNTING_EVENT_ID = XLA_E.EVENT_ID
	)PAID_AMT
, NULL PENDING_TOTAL_DAYS
, NULL PREPAID_AMT
, NULL TOTAL_AMT
, NULL ADJ_WITHIN_NEXT_12MON
--, NULL TO_BE_ADJ_AFTER_12MON
--, AIA.GL_DATE H_GL_DATE
--, AIA.INVOICE_DATE+305
--, APSA.DUE_DATE
--, TO_DATE('5/10/2024','MM/DD/RRRR') LAST_GL_COMPLETE_DATE
--, AIA.TERMS_DATE
--, TRUNC(TO_DATE('5/10/2024','MM/DD/RRRR')-AIA.INVOICE_DATE) POLICY_DAYS
--, AILA.ACCOUNTING_DATE
--, AIDA.ACCOUNTING_DATE AIDA_ACCOUNTING_DATE
--, AIA.APPROVED_AMOUNT
--, AIA.ACCTS_PAY_CODE_COMBINATION_ID
--, AIDA.DIST_CODE_COMBINATION_ID
--, AIA.PAYMENT_STATUS_FLAG
--, AIA.TERMS_ID
--, AIA.TERMS_DATE
--, AIA.VENDOR_ID
--, UPPER(AIA.DESCRIPTION) H_DESCRIPTION
--, AILA.LINE_NUMBER
--, AILA.LINE_TYPE_LOOKUP_CODE
--, AILA.ORG_ID
--, AILA.ATTRIBUTE_CATEGORY
--, (SELECT DESCRIPTION
--    FROM fnd_flex_values_vl
--    WHERE FLEX_VALUE_SET_ID =(SELECT FLEX_VALUE_SET_ID
--                FROM FND_FLEX_VALUE_SETS A
--                WHERE FLEX_VALUE_SET_NAME =  'Invoice_Tax_Type') --105..1201.211.207510...105; 112.9999.999.999.209185.9999.999.999.999.999
--    AND FLEX_VALUE_MEANING = AILA.ATTRIBUTE10) INVOICE_TAX_TYPE
--, GCC.SEGMENT2
--, GCC.SEGMENT3
--, GCC.SEGMENT6
--, GCC.SEGMENT7
--, GCC.SEGMENT8
--, GCC.PADDED_CONCATENATED_SEGMENTS CONCATENATED_SEGMENT
--, GCC.CODE_COMBINATION_ID
--, GCC2.CODE_COMBINATION_ID
--, AIDA.ACCOUNTING_EVENT_ID
--, XLA_E.ENTITY_ID
--, XLA_AE_H.AE_HEADER_ID
--, XLA_AE_H.GL_TRANSFER_DATE
--, XLA_AE_H.ACCOUNTING_BATCH_ID
FROM AP_INVOICES_ALL AIA
, AP_INVOICE_LINES_ALL AILA
, AP_INVOICE_DISTRIBUTIONS_ALL AIDA
, GL_CODE_COMBINATIONS_KFV GCC
, ORG_ORGANIZATION_DEFINITIONS OOD
, AP_PAYMENT_SCHEDULES_ALL APSA
, AP_SUPPLIERS APS
, XLA_EVENTS XLA_E --35110159
, XLA_AE_HEADERS XLA_AE_H
, XLA_AE_LINES XLA_AE_L
, GL_CODE_COMBINATIONS_KFV GCC2
WHERE 1=1
AND XLA_AE_L.CODE_COMBINATION_ID = GCC2.CODE_COMBINATION_ID
AND GCC2.GL_ACCOUNT_TYPE = 'E'
AND XLA_AE_H.AE_HEADER_ID = XLA_AE_L.AE_HEADER_ID
AND XLA_AE_H.GL_TRANSFER_DATE = (SELECT MAX(GL_TRANSFER_DATE) FROM XLA_AE_HEADERS WHERE ENTITY_ID = XLA_E.ENTITY_ID)
AND XLA_E.ENTITY_ID = XLA_AE_H.ENTITY_ID
AND AIDA.ACCOUNTING_EVENT_ID=XLA_E.EVENT_ID
AND AIDA.DIST_CODE_COMBINATION_ID = GCC.CODE_COMBINATION_ID
AND OOD.ORGANIZATION_CODE = GCC.SEGMENT1
AND OOD.OPERATING_UNIT = AIA.ORG_ID
AND AIA.VENDOR_ID = APS.VENDOR_ID
AND AIA.INVOICE_ID = APSA.INVOICE_ID
AND AILA.LINE_NUMBER = AIDA.INVOICE_LINE_NUMBER
AND AIA.INVOICE_ID = AIDA.INVOICE_ID
AND AIA.INVOICE_ID = AILA.INVOICE_ID
AND AILA.ATTRIBUTE_CATEGORY = 'MPA'
--AND AILA.LINE_TYPE_LOOKUP_CODE = 'PREPAY'
AND INVOICE_NUM = '8090005908' 

----------------------------------------------------

SELECT --XLA_AE_H.*,
  DISTINCT OOD.ORGANIZATION_NAME
, GCC.SEGMENT1 UNIT_CODE
, GCC2.SEGMENT5 EXP_CODE
, GCC.SEGMENT5 PREPAID_CODE
, GCC.SEGMENT4 DEPT
, (SELECT DESCRIPTION
    FROM FND_FLEX_VALUES_VL
    WHERE FLEX_VALUE_SET_ID =(SELECT FLEX_VALUE_SET_ID
                FROM FND_FLEX_VALUE_SETS A
                WHERE FLEX_VALUE_SET_NAME =  'Type of Expense') --105..1201.211.207510...105; 112.9999.999.999.209185.9999.999.999.999.999
    AND FLEX_VALUE_MEANING = AILA.ATTRIBUTE1) EXPENSE_HEAD
, APS.SEGMENT1 AP_CODE
, APS.VENDOR_NAME PARTY_NAME
, AIA.INVOICE_NUM BILL_NUM
, UPPER(AILA.DESCRIPTION) L_DESCRIPTION
, TO_CHAR(AILA.DEF_ACCTG_START_DATE,'DD-Mon-RR') MPA_FROM_DATE
, TO_CHAR(AILA.DEF_ACCTG_END_DATE,'DD-Mon-RR') MPA_TO_DATE
, AILA.AMOUNT ACTUAL_AMT
, NVL((SELECT AMOUNT FROM AP_INVOICE_PAYMENTS_ALL WHERE INVOICE_ID = AIA.INVOICE_ID),0) AMOUNT_PAID
, AIA.INVOICE_AMOUNT
, AIA.INVOICE_ID
, AIA.GL_DATE H_GL_DATE
, AIA.INVOICE_DATE+305
, APSA.DUE_DATE
, TO_DATE('5/10/2024','MM/DD/RRRR') LAST_GL_COMPLETE_DATE
, AIA.TERMS_DATE
, TRUNC(TO_DATE('5/10/2024','MM/DD/RRRR')-AIA.INVOICE_DATE) POLICY_DAYS
, AILA.ACCOUNTING_DATE
, AIDA.ACCOUNTING_DATE AIDA_ACCOUNTING_DATE
, AIA.APPROVED_AMOUNT
, AIA.ACCTS_PAY_CODE_COMBINATION_ID
, AIDA.DIST_CODE_COMBINATION_ID
, AIA.PAYMENT_STATUS_FLAG
, AIA.TERMS_ID
, AIA.TERMS_DATE
, AIA.VENDOR_ID
, UPPER(AIA.DESCRIPTION) H_DESCRIPTION
, AILA.LINE_NUMBER
, AILA.LINE_TYPE_LOOKUP_CODE
, AILA.ORG_ID
, AILA.ATTRIBUTE_CATEGORY
, (SELECT DESCRIPTION
    FROM fnd_flex_values_vl
    WHERE FLEX_VALUE_SET_ID =(SELECT FLEX_VALUE_SET_ID
                FROM FND_FLEX_VALUE_SETS A
                WHERE FLEX_VALUE_SET_NAME =  'Invoice_Tax_Type') --105..1201.211.207510...105; 112.9999.999.999.209185.9999.999.999.999.999
    AND FLEX_VALUE_MEANING = AILA.ATTRIBUTE10) INVOICE_TAX_TYPE
, GCC.SEGMENT2
, GCC.SEGMENT3
, GCC.SEGMENT6
, GCC.SEGMENT7
, GCC.SEGMENT8
, GCC.PADDED_CONCATENATED_SEGMENTS CONCATENATED_SEGMENT
, GCC.CODE_COMBINATION_ID
, GCC2.CODE_COMBINATION_ID
, AIDA.ACCOUNTING_EVENT_ID
, XLA_E.ENTITY_ID
--, XLA_AE_H.AE_HEADER_ID
, XLA_AE_H.GL_TRANSFER_DATE
, XLA_AE_H.ACCOUNTING_BATCH_ID
FROM AP_INVOICES_ALL AIA
, AP_INVOICE_LINES_ALL AILA
, AP_INVOICE_DISTRIBUTIONS_ALL AIDA
, GL_CODE_COMBINATIONS_KFV GCC
, ORG_ORGANIZATION_DEFINITIONS OOD
, AP_PAYMENT_SCHEDULES_ALL APSA
, AP_SUPPLIERS APS
, XLA_EVENTS XLA_E --35110159
, XLA_AE_HEADERS XLA_AE_H
, XLA_AE_LINES XLA_AE_L
, GL_CODE_COMBINATIONS_KFV GCC2
WHERE 1=1
AND XLA_AE_L.CODE_COMBINATION_ID = GCC2.CODE_COMBINATION_ID
AND GCC2.GL_ACCOUNT_TYPE = 'E'
AND XLA_AE_H.AE_HEADER_ID = XLA_AE_L.AE_HEADER_ID
AND XLA_AE_H.GL_TRANSFER_DATE = (SELECT MAX(GL_TRANSFER_DATE) FROM XLA_AE_HEADERS WHERE ENTITY_ID = XLA_E.ENTITY_ID)
AND XLA_E.ENTITY_ID = XLA_AE_H.ENTITY_ID
AND AIDA.ACCOUNTING_EVENT_ID=XLA_E.EVENT_ID
AND AIDA.DIST_CODE_COMBINATION_ID = GCC.CODE_COMBINATION_ID
AND OOD.ORGANIZATION_CODE = GCC.SEGMENT1
AND OOD.OPERATING_UNIT = AIA.ORG_ID
AND AIA.VENDOR_ID = APS.VENDOR_ID
AND AIA.INVOICE_ID = APSA.INVOICE_ID
AND AILA.LINE_NUMBER = AIDA.INVOICE_LINE_NUMBER
AND AIA.INVOICE_ID = AIDA.INVOICE_ID
AND AIA.INVOICE_ID = AILA.INVOICE_ID
AND AILA.ATTRIBUTE_CATEGORY = 'MPA'
--AND AILA.LINE_TYPE_LOOKUP_CODE = 'PREPAY'
AND INVOICE_NUM = '92605248001662' --'8090005908' --'90000023E0006366.'

----------------------------------------------


SELECT *
     FROM FND_FLEX_VALUES
     WHERE 1=1
     AND SYSDATE < NVL(END_DATE_ACTIVE,SYSDATE+1)
     AND ENABLED_FLAG = 'Y'
     AND FLEX_VALUE = '1201'
     AND FLEX_VALUE_SET_ID = (SELECT FLEX_VALUE_SET_ID
            FROM FND_FLEX_VALUE_SETS A
            WHERE FLEX_VALUE_SET_NAME =  'AUPL_Location')
            
select *
from dba_objects
where upper(object_name) like 'FND%FLEX%V' --FND_FLEX_VSET_V, FND_FLEX_VALUESET_V

SELECT *
FROM FND_FLEX_VALUESET_V
WHERE FLEX_VALUE_SET_NAME LIKE '%AUPL_Location'

SELECT *
FROM FND_FLEX_VSET_V
WHERE PARENT_FLEX_VALUE_SET_ID = 1021568

SELECT *
FROM AP_INVOICES_ALL
WHERE ROWNUM < 10 AND ORG_ID = 288 AND INVOICE_AMOUNT > 0 AND PAYMENT_STATUS_FLAG = 'N'
ORDER BY CREATION_DATE DESC

select *
from AP_PAYMENT_SCHEDULES_ALL APSA
where INVOICE_ID = 4876473

SELECT *
FROM AP_INVOICE_PAYMENTS_ALL
WHERE INVOICE_ID = 4876473






select ORGANIZATION_NAME
from ORG_ORGANIZATION_DEFINITIONS
where 1=1
and ORGANIZATION_CODE ='105'
and OPERATING_UNIT = 288


select *
from hz_parties
where party_number = '1201'

select *
from hz_party_sites
where party_id = 12312

select *
from hr_operating_units
where organization_id = 268 


select segment1||'.'||segment2||'.'||segment3||'.'||segment4||'.'||segment5||'.'||segment6||'.'||segment7||'.'||segment8
from GL_CODE_COMBINATIONS GCC
where code_combination_id = 309504

SELECT *
FROM AP_SUPPLIERS
WHERE VENDOR_ID = 184954

SELECT *
FROM AP_TERMS
WHERE TERM_ID = 10000


select *
from dba_objects
where upper(object_name) like 'FND%ID%FLEX%'
AND OBJECT_TYPE NOT IN ('PACKAGE','INDEX','SEQUENCE')
AND OWNER = 'APPS'



SELECT *
FROM FND_APPLICATION_VL
WHERE UPPER(APPLICATION_NAME) LIKE '%INVOICE%'