CREATE PACKAGE XXAU_CREATE_CUSTOMER_SITE_PKG
IS

    /***************************************************************************************************
     * Global Variables : Declaration and Initialization
     ***************************************************************************************************/
	 GN_USER_ID NUMBER := FND_PROFILE.VALUE('USER_ID');
	 GN_ORG_ID NUMBER := FND_PROFILE.VALUE('ORG_ID');
	 GN_RESP_ID NUMBER := FND_PROFILE.VALUE('RESP_ID');
	 GN_RESP_APPL_ID NUMBER := FND_PROFILE.VALUE('RESP_APPL_ID');
    /****************************************************************************************************/
	 

	FUNCTION CREATE_CUST_SITE_USES (P_CUST_ACCT_SITE_ID NUMBER,P_SITE_USE_CODE VARCHAR2,P_LOCATION VARCHAR2) 
		RETURN NUMBER;
		
	FUNCTION CREATE_CUST_ACCT_SITE (P_CUST_ACCOUNT_ID NUMBER,P_PARTY_SITE_ID NUMBER) 
		RETURN NUMBER;
		
	FUNCTION CREATE_CUST_ACCOUNT (P_ORGANIZATION_NAME VARCHAR2,P_PARTY_ID NUMBER, P_ACCOUNT_NAME VARCHAR2) 
		RETURN NUMBER;
		
	FUNCTION CREATE_PARTY_SITE (P_PARTY_ID NUMBER, P_LOCATION_ID NUMBER) 
		RETURN NUMBER;
		
	FUNCTION CREATE_PARTY (P_ORGANIZATION_NAME VARCHAR2) 
		RETURN NUMBER;
		
	FUNCTION CREATE_LOCATION (P_ADDRESS1 VARCHAR2,P_ADDRESS2 VARCHAR2, P_CITY VARCHAR2, P_POSTAL_CODE NUMBER,P_STATE VARCHAR2,P_COUNTRY VARCHAR2) 
		RETURN NUMBER;
		
	PROCEDURE CREATE_CUSTOMER_AND_SITES ;
	
	PROCEDURE VALIDATE_REQUIRED ;
	
	PROCEDURE MAIN (ERRBUFF OUT VARCHAR2, RETCODE OUT VARCHAR2) ;
	
END XXAU_CREATE_CUSTOMER_SITE_PKG;