CREATE OR REPLACE PACKAGE APPS.XXAU_CREATE_CUSTOMER_SITE_PKG
IS

    /***************************************************************************************************
     * Global Variables : Declaration and Initialization
     ***************************************************************************************************/
	 GN_USER_ID NUMBER := FND_PROFILE.VALUE('USER_ID');
	 GN_ORG_ID NUMBER := FND_PROFILE.VALUE('ORG_ID');
	 GN_RESP_ID NUMBER := FND_PROFILE.VALUE('RESP_ID');
	 GN_RESP_APPL_ID NUMBER := FND_PROFILE.VALUE('RESP_APPL_ID');
    /****************************************************************************************************/
	 
	PROCEDURE CREATE_CONTACT_ORG ( 	P_PARTY_ID IN NUMBER
							, P_CONTACT_PERSON IN VARCHAR2
							, P_MSG OUT VARCHAR2); 
	
	PROCEDURE CREATE_CODE_COMBINATION (P_ORG_ID 		IN NUMBER
									, P_INV_ORG 		IN NUMBER
									, P_AGENCY_ID 		IN NUMBER
									, P_CENTRE_NUMBER 	IN VARCHAR2
									, P_AGENCY_NAME 	IN VARCHAR2
									, P_CCID			OUT NUMBER
									, P_MSG 			OUT VARCHAR2);
	
	PROCEDURE CREATE_CONTACT_POINT_SITE_LVL ( P_PARTY_SITE_ID IN NUMBER
											, P_PHONE IN NUMBER 
											, P_EMAIL IN VARCHAR2
											, P_TABLE IN VARCHAR2
											, P_PHONE_CONTACT_POINT_ID OUT NUMBER
											, P_EMAIL_CONTACT_POINT_ID OUT NUMBER
											, P_MSG OUT VARCHAR2);

	PROCEDURE CREATE_CUST_SITE_USES (P_CUST_ACCT_SITE_ID IN NUMBER
									,P_SITE_USE_CODE IN VARCHAR2
									,P_CUSTOMER_TYPE IN VARCHAR2
									,P_LOCATION IN VARCHAR2
									,P_CENTRE_NUMBER IN VARCHAR2
									,P_PRIMARY_FLAG IN VARCHAR2
									,P_PAYMENT_TERMS IN VARCHAR2
									,P_REC_ACCOUNT IN VARCHAR2
									,P_SITE_USE_ID OUT NUMBER
									,P_CCID	OUT NUMBER
									,P_MSG OUT VARCHAR2
									)    ;
		
	PROCEDURE CREATE_CUST_ACCT_SITE (P_CUST_ACCOUNT_ID IN NUMBER
								,P_PARTY_SITE_ID IN NUMBER
								,P_CUSTOMER_TYPE IN VARCHAR2
								,P_CUST_ACCT_SITE_ID OUT NUMBER
								,P_MSG OUT VARCHAR2
								) ;
		
	PROCEDURE CREATE_CUST_ACCOUNT (    P_ORGANIZATION_NAME IN VARCHAR2
								,  P_ACCOUNT_NAME IN VARCHAR2
								,  P_ABC_TYPE IN VARCHAR2
								,  P_AGENCY_ID IN NUMBER
								,  P_CUSTOMER_TYPE IN VARCHAR2
								,  P_CUSTOMER_CLASS_CODE IN VARCHAR2
								,  P_UNIT IN VARCHAR2
								,  P_PARTY_ID IN OUT NUMBER
								,  P_CUST_ACCOUNT_ID OUT NUMBER
								,  P_PARTY_NUMBER OUT VARCHAR2
								,  P_PROFILE_ID OUT NUMBER
								,  P_ACCOUNT_NUMBER OUT VARCHAR2
								,  P_MSG OUT VARCHAR2
								) ;
		
	PROCEDURE CREATE_PARTY_SITE ( P_PARTY_ID IN NUMBER
							, P_LOCATION_ID IN NUMBER
							, P_CUSTOMER_TYPE IN VARCHAR2
							, P_STATION_NAME IN VARCHAR2
							, P_PARTY_SITE_ID OUT NUMBER
							, P_PARTY_SITE_NUM OUT VARCHAR2
							, P_MSG OUT VARCHAR2)   ;
		
	PROCEDURE CREATE_PARTY (P_ORGANIZATION_NAME IN VARCHAR2
						,  P_PARTY_ID OUT NUMBER
						,  P_PARTY_NUMBER OUT VARCHAR2
						,  P_PROFILE_ID OUT NUMBER
						,  P_MSG OUT VARCHAR2)  ;
		
	PROCEDURE CREATE_LOCATION (	   P_ADDRESS1 IN VARCHAR2
							,  P_ADDRESS2 IN VARCHAR2
							,  P_ADDRESS3 IN VARCHAR2
							,  P_ADDRESS4 IN VARCHAR2
							,  P_CITY  IN VARCHAR2
							,  P_POSTAL_CODE IN NUMBER
							,  P_STATE IN VARCHAR2
							,  P_COUNTY IN VARCHAR2
							,  P_COUNTRY IN VARCHAR2
							,  P_LOCATION1 IN VARCHAR2
							,  P_LOCATION_ID OUT NUMBER
							,  P_MSG OUT VARCHAR2) ;
		
	PROCEDURE CREATE_SAFALTA_CUST_AND_SITES ;	
	
	PROCEDURE CREATE_CUSTOMER_AND_SITES ;
	
	PROCEDURE CREATE_CUSTOMERS_SITES ;
	
	PROCEDURE VALIDATE_REQUIRED ;
	
	PROCEDURE LOAD_DATA;
	
	PROCEDURE MAIN (ERRBUFF OUT VARCHAR2, RETCODE OUT VARCHAR2) ;
	
END XXAU_CREATE_CUSTOMER_SITE_PKG;
/
