Program : TI - XXAU Customer & Site Creation Process
Short Name: XXAU_CREATE_CUSTOMER_SITE

Executable : XXAU_CREATE_CUSTOMER_SITE
Executable Short Name : XXAU_CREATE_CUSTOMER_SITE
Execution File Name : XXAU_CREATE_CUSTOMER_SITE_PKG.MAIN

Package : XXAU_CREATE_CUSTOMER_SITE_PKG

------------------------------------------------------------------
Custom Tables : 

1. AU_CUSTOMER_MASTER_NEW_TEST
2. AU_CUSTOMER_SHIP_TO_TEST
3. XXAU_CUSTOMER_DETAILS_TEST

-----------------------------------------------------------------
Query to check data before Loading Progam
-----------------------------------------
-- Those Customers whose only sites has to be create and does not belongs to Safalta Unit
SELECT *
		FROM AU_CUSTOMER_MASTER_NEW_TEST A
		WHERE AGENCY_ID  IN (SELECT AGENCY_ID 
							FROM XXAU_AGENCY_APPROVAL_DTL_TEST
							WHERE TRUNC(CREATION_DATE) >='01-OCT-2024'
							AND APPROVE_REJECT = 'A'
							AND AGREEMENT_FLAG = 'Y')
		AND ERP_CUSTOMER_NUMBER IS NOT NULL
		AND ERP_CUSTOMER_ID IS NOT NULL
		AND ERP_PARTY_ID IS NOT NULL
		AND EXISTS (SELECT 1 
				FROM AU_CUSTOMER_SHIP_TO_TEST 
				WHERE AGENCY_ID = A.AGENCY_ID 
				AND UPPER(PROUCT_NAME) NOT LIKE '%SAFALTA%' 
				AND ERP_CUSTOMER_NUMBER IS NULL
				AND ERP_SITE_USE_ID IS NULL)
	;
	
--- SHIP TO
SELECT *
		FROM AU_CUSTOMER_SHIP_TO_TEST A
		WHERE AGENCY_ID IN (SELECT AGENCY_ID 
							FROM XXAU_AGENCY_APPROVAL_DTL_TEST
							WHERE TRUNC(CREATION_DATE) >='01-OCT-2024'
							AND APPROVE_REJECT = 'A'
							AND AGREEMENT_FLAG = 'Y')						
		AND UPPER(PROUCT_NAME) NOT LIKE '%SAFALTA%' 
		AND CUSTOMER_SHIP_ID IS NULL
		AND ERP_PARTY_ID IS NULL
		AND ERP_SITE_USE_ID IS NULL
		AND ERP_CUSTOMER_NUMBER IS NULL
		AND ERP_CUSTOMER_ID IS NULL
		AND AGENCY_ID = :P_AGENCY_ID
	;

----------------------------------------------------------------------
-- Those Customers whose account and ship to sites has to be create and does not belongs to Safalta Unit
----------------------------------------------------------------------
SELECT *
	FROM AU_CUSTOMER_MASTER_NEW_TEST A
	WHERE AGENCY_ID  IN (SELECT AGENCY_ID 
						FROM XXAU_AGENCY_APPROVAL_DTL_TEST
						WHERE TRUNC(CREATION_DATE) >='01-OCT-2024'
						AND APPROVE_REJECT = 'A'
						AND AGREEMENT_FLAG = 'Y')
	AND ERP_PARTY_ID IS NULL
	AND ERP_CUSTOMER_NUMBER IS NULL
	AND ERP_CUSTOMER_ID IS NULL
	AND EXISTS (SELECT 1 
				FROM AU_CUSTOMER_SHIP_TO_TEST 
				WHERE AGENCY_ID = A.AGENCY_ID 
				AND UPPER(PROUCT_NAME) NOT LIKE '%SAFALTA%' 
				AND ERP_CUSTOMER_NUMBER IS NULL
				AND ERP_SITE_USE_ID IS NULL)
	;
	
-- SHIP TO Details
SELECT *
		FROM AU_CUSTOMER_SHIP_TO_TEST A
		WHERE AGENCY_ID IN (SELECT AGENCY_ID 
							FROM XXAU_AGENCY_APPROVAL_DTL_TEST
							WHERE TRUNC(CREATION_DATE) >='01-OCT-2024'
							AND APPROVE_REJECT = 'A'
							AND AGREEMENT_FLAG = 'Y')						
		AND UPPER(PROUCT_NAME) NOT LIKE '%SAFALTA%' 
		AND CUSTOMER_SHIP_ID IS NULL
		AND ERP_PARTY_ID IS NULL
		AND ERP_SITE_USE_ID IS NULL
		AND ERP_CUSTOMER_NUMBER IS NULL
		AND ERP_CUSTOMER_ID IS NULL
		AND AGENCY_ID = :P_AGENCY_ID
	;
-----------------------------------------------------------------------------------------------
-- Those Customers whose account and ship to sites has to be create and belongs to Safalta Unit
-----------------------------------------------------------------------------------------------
SELECT *
	FROM AU_CUSTOMER_MASTER_NEW_TEST A
	WHERE AGENCY_ID  IN (SELECT AGENCY_ID 
						FROM XXAU_AGENCY_APPROVAL_DTL_TEST
						WHERE TRUNC(CREATION_DATE) >='01-OCT-2024'
						AND APPROVE_REJECT = 'A'
						AND AGREEMENT_FLAG = 'Y')
	--AND ERP_CUSTOMER_NUMBER IS NULL
	AND EXISTS (SELECT 1 
				FROM AU_CUSTOMER_SHIP_TO_TEST 
				WHERE AGENCY_ID = A.AGENCY_ID 
				AND UPPER(PROUCT_NAME) LIKE '%SAFALTA%' 
				AND ERP_CUSTOMER_NUMBER IS NULL
				AND ERP_SITE_USE_ID IS NULL)
	;

-- SHIP TO Details
SELECT *
		FROM AU_CUSTOMER_SHIP_TO_TEST A
		WHERE AGENCY_ID IN (SELECT AGENCY_ID 
							FROM XXAU_AGENCY_APPROVAL_DTL_TEST
							WHERE TRUNC(CREATION_DATE) >='01-OCT-2024'
							AND APPROVE_REJECT = 'A'
							AND AGREEMENT_FLAG = 'Y')						
		AND UPPER(PROUCT_NAME) LIKE '%SAFALTA%' 
		AND CUSTOMER_SHIP_ID IS NULL
		AND ERP_PARTY_ID IS NULL
		AND ERP_SITE_USE_ID IS NULL
		AND ERP_CUSTOMER_NUMBER IS NULL
		AND ERP_CUSTOMER_ID IS NULL
		AND AGENCY_ID = :P_AGENCY_ID
	;