SELECT 
AGENCY_ACCOUNT_TYPE
, AGENCY_AREA_TYPE
, AGENCY_ID
, AGENCY_NAME
, AGREEMENT_FLAG
, APPROVE_DATE_SHIP
, APPROVE_REJECT
, AREA_TYPE_SHIP
, CENTRE_NUMBER
, CREATED_BY
, CREATED_USER_NAME
, CREATION_DATE
, DAK_CODE
, DAK_NAME
, ERP_CUST_ACCT_SITE_ID
, ERP_CUSTOMER_ID
, ERP_CUSTOMER_NUMBER
, ERP_LOCATION_ID 
, ERP_PARTY_ID
, ERP_PROCESS_FLAG
, ERP_SITE_USE_ID
, ERROR_MSZ
, INV_ORG
, LAST_UPDATED_BY
, LAST_UPDATED_DATE
, MAIN_SUB
, NAME_OF_CENTRE
, PAYMENT_TERM
, PROUCT_NAME
, REMARK1
, SUPPLY_START_DATE
, SUPPLY_TYPE
, UPDATED_USER_NAME
FROM AUCUSTOM.XXAU_AGENCY_APPROVAL_DETIALS@ebstohr
WHERE TRUNC(CREATION_DATE) >='01-OCT-2024'
AND APPROVE_REJECT = 'A'
AND AGREEMENT_FLAG = 'Y'