PROJECT REQUIRED OBJECTS
------------------------------------------ 
XXAU_AR_TRNSP_RCPT_ERR
CREATE TABLE APPS.XXAU_AR_TRNSP_RCPT_ERR
(
  CONC_RCPT_ID          NUMBER,
  COMPOSITE_RECEIPT_ID  NUMBER,
  STATUS                VARCHAR2(1 BYTE),
  ERROR_MESSAGE         VARCHAR2(4000 BYTE)
)

------------------------------------------
REQUIRED PACKAGE
------------------------------------------
XXAU_COMP_RCPT_CREATION_PKG.pkb / sql
XXAU_COMP_RCPT_CREATION_PKG.pks / sql
------------------------------------------

REQUIRED VALIDATIONS
--------------------
FOR ATTRIBUTES:
---------------
ATTRIBUTE2
---------------
BEGIN
	SELECT FLEX_VALUE
	INTO J.ATTRIBUTE2 -- SHOULD AVAILABLE IN VALUESET -> XXAU_CHECK_LOCAL
	FROM FND_FLEX_VALUES
	WHERE 1=1
	AND SYSDATE < NVL(END_DATE_ACTIVE,SYSDATE+1)
	AND ENABLED_FLAG = 'Y'
	AND FLEX_VALUE_SET_ID = (SELECT FLEX_VALUE_SET_ID
								FROM FND_FLEX_VALUE_SETS A
								WHERE FLEX_VALUE_SET_NAME =  'XXAU_CHECK_LOCAL')
	AND FLEX_VALUE = TRIM(J.ATTRIBUTE2);
EXCEPTION WHEN OTHERS THEN
	J.ATTRIBUTE2 := NULL;
	J.PROCESS_FLAG := 'E';
	LC_ERROR:=LC_ERROR||'XXAU_CHECK_LOCAL VALUESET error: '||J.ATTRIBUTE2||'; '||SQLCODE||'-'||SQLERRM||'; ';
	DBMS_OUTPUT.PUT_LINE('XXAU_CHECK_LOCAL VALUESET error FOR ATTRIBUTE2: '||J.ATTRIBUTE2||'; '||SQLCODE||'-'||SQLERRM||'; ');
END;
---------------
ATTRIBUTE3
---------------
BEGIN
	SELECT FLEX_VALUE
	INTO J.ATTRIBUTE3
	FROM FND_FLEX_VALUES
	WHERE 1=1
	AND SYSDATE < NVL(END_DATE_ACTIVE,SYSDATE+1)
	AND ENABLED_FLAG = 'Y'
	AND FLEX_VALUE_SET_ID = (SELECT FLEX_VALUE_SET_ID
								FROM FND_FLEX_VALUE_SETS A
								WHERE FLEX_VALUE_SET_NAME =  'AR_SRS_YES_NO')
	AND FLEX_VALUE = TRIM(J.ATTRIBUTE3);
EXCEPTION WHEN OTHERS THEN
	J.ATTRIBUTE3 := NULL;
	J.PROCESS_FLAG := 'E';
	LC_ERROR:=LC_ERROR||'AR_SRS_YES_NO VALUESET error: '||J.ATTRIBUTE3||'; '||SQLCODE||'-'||SQLERRM||'; ';
	DBMS_OUTPUT.PUT_LINE('AR_SRS_YES_NO VALUESET error FOR ATTRIBUTE3: '||J.ATTRIBUTE3||'; '||SQLCODE||'-'||SQLERRM||'; ');
END;
---------------
ATTRIBUTE4
---------------
BEGIN
	SELECT FLEX_VALUE
	INTO J.ATTRIBUTE4
	FROM FND_FLEX_VALUES
	WHERE 1=1
	AND SYSDATE < NVL(END_DATE_ACTIVE,SYSDATE+1)
	AND ENABLED_FLAG = 'Y'
	AND FLEX_VALUE_SET_ID = (SELECT FLEX_VALUE_SET_ID
								FROM FND_FLEX_VALUE_SETS A
								WHERE FLEX_VALUE_SET_NAME =  'AR_SRS_YES_NO')
	AND FLEX_VALUE = TRIM(ATTRIBUTE4);
EXCEPTION WHEN OTHERS THEN
	J.ATTRIBUTE4 := NULL;
	J.PROCESS_FLAG := 'E';
	LC_ERROR:=LC_ERROR||'AR_SRS_YES_NO VALUESET error: '||J.ATTRIBUTE4||'; '||SQLCODE||'-'||SQLERRM||'; ';
	DBMS_OUTPUT.PUT_LINE('AR_SRS_YES_NO VALUESET error FOR ATTRIBUTE4: '||J.ATTRIBUTE4||'; '||SQLCODE||'-'||SQLERRM||'; ');
END;
---------------
ATTRIBUTE5
---------------
BEGIN
	SELECT FLEX_VALUE
	INTO J.ATTRIBUTE5
	FROM FND_FLEX_VALUES
	WHERE 1=1
	AND SYSDATE < NVL(END_DATE_ACTIVE,SYSDATE+1)
	AND ENABLED_FLAG = 'Y'
	AND FLEX_VALUE_SET_ID = (SELECT FLEX_VALUE_SET_ID
								FROM FND_FLEX_VALUE_SETS A
								WHERE FLEX_VALUE_SET_NAME =  'AR_SRS_YES_NO')
	AND FLEX_VALUE = TRIM(ATTRIBUTE5);
EXCEPTION WHEN OTHERS THEN
	J.ATTRIBUTE5 := NULL;
	J.PROCESS_FLAG := 'E';
	LC_ERROR:=LC_ERROR||'AR_SRS_YES_NO VALUESET error: '||J.ATTRIBUTE5||'; '||SQLCODE||'-'||SQLERRM||'; ';
	DBMS_OUTPUT.PUT_LINE('AR_SRS_YES_NO VALUESET error FOR ATTRIBUTE5: '||J.ATTRIBUTE5||'; '||SQLCODE||'-'||SQLERRM||'; ');
END;
---------------
ATTRIBUTE6
---------------
BEGIN
	SELECT FLEX_VALUE
	INTO J.ATTRIBUTE6
	FROM FND_FLEX_VALUES
	WHERE 1=1
	AND SYSDATE < NVL(END_DATE_ACTIVE,SYSDATE+1)
	AND ENABLED_FLAG = 'Y'
	AND FLEX_VALUE_SET_ID = (SELECT FLEX_VALUE_SET_ID
								FROM FND_FLEX_VALUE_SETS A
								WHERE FLEX_VALUE_SET_NAME =  'AR_SRS_YES_NO')
	AND FLEX_VALUE = TRIM(ATTRIBUTE6);
EXCEPTION WHEN OTHERS THEN
	J.ATTRIBUTE6 := NULL;
	J.PROCESS_FLAG := 'E';
	LC_ERROR:=LC_ERROR||'AR_SRS_YES_NO VALUESET error: '||J.ATTRIBUTE6||'; '||SQLCODE||'-'||SQLERRM||'; ';
	DBMS_OUTPUT.PUT_LINE('AR_SRS_YES_NO VALUESET error FOR ATTRIBUTE6: '||J.ATTRIBUTE6||'; '||SQLCODE||'-'||SQLERRM||'; ');
END;
---------------
ATTRIBUTE7
----------
BEGIN
	SELECT FLEX_VALUE
	INTO J.ATTRIBUTE7 --> Bank Name SHOULD AVAILABLE IN  VALUESET -> XXA_BANK_NAME
	FROM FND_FLEX_VALUES
	WHERE 1=1
	AND SYSDATE < NVL(END_DATE_ACTIVE,SYSDATE+1)
	AND ENABLED_FLAG = 'Y'
	AND FLEX_VALUE_SET_ID = (SELECT FLEX_VALUE_SET_ID
								FROM FND_FLEX_VALUE_SETS A
								WHERE FLEX_VALUE_SET_NAME =  'XXA_BANK_NAME')
	AND FLEX_VALUE = TRIM(J.ATTRIBUTE7);
EXCEPTION WHEN OTHERS THEN
	J.ATTRIBUTE7 := NULL;
	J.PROCESS_FLAG := 'E';
	LC_ERROR:=LC_ERROR||'XXA_BANK_NAME VALUESET error: '||J.ATTRIBUTE7||'; '||SQLCODE||'-'||SQLERRM||'; ';
	DBMS_OUTPUT.PUT_LINE('Receipt Method ID fetching error FOR ATTRIBUTE7: '||J.ATTRIBUTE7||'; '||SQLCODE||'-'||SQLERRM||'; ');
END;

---------------
ATTRIBUTE8
---------------
BEGIN
	SELECT FLEX_VALUE
	INTO J.ATTRIBUTE8
	FROM FND_FLEX_VALUES
	WHERE 1=1
	AND SYSDATE < NVL(END_DATE_ACTIVE,SYSDATE+1)
	AND ENABLED_FLAG = 'Y'
	AND FLEX_VALUE_SET_ID = (SELECT FLEX_VALUE_SET_ID
								FROM FND_FLEX_VALUE_SETS A
								WHERE FLEX_VALUE_SET_NAME =  'XXA_BANK_ACCOUNT_NUMBER')
	AND FLEX_VALUE = TRIM(J.ATTRIBUTE8);
EXCEPTION WHEN OTHERS THEN
	J.ATTRIBUTE8 := NULL;
	J.PROCESS_FLAG := 'E';
	LC_ERROR:=LC_ERROR||'XXA_BANK_ACCOUNT_NUMBER VALUESET Error: '||J.ATTRIBUTE8||'; '||SQLCODE||'-'||SQLERRM||'; ';
	DBMS_OUTPUT.PUT_LINE('XXA_BANK_ACCOUNT_NUMBER VALUESET Error FOR ATTRIBUTE8: '||J.ATTRIBUTE8||'; '||SQLCODE||'-'||SQLERRM||'; ');
END;

---------------
BANK_ACC_NAME
---------------
LC_DUMMY := 'DUMMY BANK '||REGEXP_REPLACE(J.BANK_ACC_NAME, '\s*cash', '', 1, 0, 'i');
				
-- FOR CORRECT DUMMY RECEIPT METHOD ID -- ADDDED ON 12-FEB-2026 BY AKALA
BEGIN
	SELECT RECEIPT_METHOD_ID
	INTO LN_RECEIPT_METHOD_ID_REC
	FROM AR_RECEIPT_METHODS
	WHERE 1=1
	AND UPPER(NAME) = UPPER(LC_DUMMY)
	AND REGEXP_LIKE(NAME,'[^-]')
	;
	
	/*
	SELECT ARRM.RECEIPT_METHOD_ID
	INTO LN_RECEIPT_METHOD_ID_REC
	FROM AR_RECEIPT_METHODS ARRM
	, AR_RECEIPT_METHOD_ACCOUNTS_ALL AR_RMA
	, CE_BANK_ACCT_USES_ALL CE_BAUA
	WHERE 1=1
	AND ARRM.RECEIPT_METHOD_ID = AR_RMA.RECEIPT_METHOD_ID
	AND AR_RMA.REMIT_BANK_ACCT_USE_ID = CE_BAUA.BANK_ACCT_USE_ID
	AND CE_BAUA.BANK_ACCT_USE_ID = 10498
	AND AR_RMA.ORG_ID = :L_ORG_ID
	*/
	
EXCEPTION WHEN OTHERS THEN
	LN_RECEIPT_METHOD_ID_REC := NULL;
	J.PROCESS_FLAG := 'E';
	LC_ERROR:=LC_ERROR||'Receipt Method error: '||LC_DUMMY||'; '||SQLCODE||'-'||SQLERRM||'; ';
	DBMS_OUTPUT.PUT_LINE('Receipt Method ID fetching error FOR ATTRIBUTE7: '||J.ATTRIBUTE7||'; '||SQLCODE||'-'||SQLERRM||'; ');
END;
---------------
RECEIVABLES_TRX_ID - ATTRIBUTE9
---------------
LC_RECE_TRX_NAME:= SUBSTR(J.ATTRIBUTE9,1,3)||'%MISC%RECEIPTS';
BEGIN
	SELECT RECEIVABLES_TRX_ID
	INTO LN_RECEIVABLES_TRX_ID
	FROM AR_RECEIVABLES_TRX_ALL
	WHERE UPPER(NAME) LIKE LC_RECE_TRX_NAME ;
EXCEPTION
WHEN OTHERS THEN
	LN_RECEIVABLES_TRX_ID:=NULL;
	J.PROCESS_FLAG := 'E';
	LC_ERROR:=LC_ERROR||'RECEIVABLES_TRX_ID error: '||LC_RECE_TRX_NAME||'; '||SQLCODE||'-'||SQLERRM||'; ';
	DBMS_OUTPUT.PUT_LINE('RECEIVABLES_TRX_ID fetching error FOR LC_RECE_TRX_NAME AT ATTRIBUTE9: '||J.ATTRIBUTE9||'; '||SQLCODE||'-'||SQLERRM||'; ');
END;
---------------
ATTRIBUTE14
---------------
BEGIN
	SELECT FLEX_VALUE
	INTO J.ATTRIBUTE14 -- SHOULD AVAILABLE IN Provisional Receipt VALUESET-> XXA_Prov_Receipt
	FROM FND_FLEX_VALUES
	WHERE 1=1
	AND SYSDATE < NVL(END_DATE_ACTIVE,SYSDATE+1)
	AND ENABLED_FLAG = 'Y'
	AND FLEX_VALUE_SET_ID = (SELECT FLEX_VALUE_SET_ID
								FROM FND_FLEX_VALUE_SETS A
								WHERE FLEX_VALUE_SET_NAME =  'XXA_Prov_Receipt')
	AND FLEX_VALUE = TRIM(J.ATTRIBUTE14);
EXCEPTION WHEN OTHERS THEN
	J.ATTRIBUTE14 := NULL;
	J.PROCESS_FLAG := 'E';
	LC_ERROR:=LC_ERROR||'XXA_Prov_Receipt VALUESET Error: '||J.ATTRIBUTE14||'; '||SQLCODE||'-'||SQLERRM||'; ';
	DBMS_OUTPUT.PUT_LINE('XXA_Prov_Receipt VALUESET Error FOR ATTRIBUTE14: '||J.ATTRIBUTE14||'; '||SQLCODE||'-'||SQLERRM||'; ');
END;
---------------
GL OPEN PERIOD
---------------
SELECT DISTINCT 
    PERIOD_NAME,
    START_DATE,
    END_DATE,
    CLOSING_STATUS
FROM
    GL_PERIOD_STATUSES
WHERE
    APPLICATION_ID = 101          -- GL
    --AND CLOSING_STATUS = 'O'      -- O = OPEN
    AND TO_CHAR(START_DATE,'RRRR') = TO_CHAR(SYSDATE,'RRRR')
ORDER BY
    START_DATE DESC;
---------------


DECLARE
LC_ERRBUF VARCHAR2(100);
LC_RETCODE VARCHAR2(100);
BEGIN
 XXAU_COMP_RCPT_CREATION_PKG.MAIN(LC_ERRBUF,LC_RETCODE);
END;

SELECT PROCESS_FLAG, PROCESS_MESSAGE, CONS_RCPT_NO, A.*
FROM XXAU_AR_TRANS_ERP_RCPT_T A
WHERE 1=1
AND CONS_RCPT_NO IS NOT NULL

SELECT *
FROM XXAU_AR_TRNSP_RCPT_ERR

UPDATE XXAU_AR_TRANS_ERP_RCPT_T
SET PROCESS_FLAG=NULL
, PROCESS_MESSAGE = NULL
--, CONS_RCPT_NO = 10
--WHERE CONS_RCPT_NO = 10

TRUNCATE TABLE XXAU_AR_TRNSP_RCPT_ERR

DELETE AR_CASH_RECEIPTS_ALL
WHERE CASH_RECEIPT_ID IN (SELECT CASH_RECEIPT_ID
                            FROM AR_CASH_RECEIPTS_ALL
                            WHERE RECEIPT_NUMBER IN ('C9.1','C9.2','C9.3','C10.1', 'C10.2', 'C10', 'C10.3', 'C11.1', 'C11.2', 'C11.3', 'C11', 'C9', 'C7.9', 'C7.10', 'C7.11')
                            )
							
							
EDIT XXAU_AR_TRANS_ERP_RCPT_T A
WHERE RECEIPT_DATE|| BANK_ACC_ID|| BANK_ACC_NUMBER|| ATTRIBUTE7|| ATTRIBUTE8|| RECEIPT_METHOD_ID IN 
(SELECT RECEIPT_DATE|| BANK_ACC_ID|| BANK_ACC_NUMBER|| ATTRIBUTE7|| ATTRIBUTE8|| RECEIPT_METHOD_ID
FROM XXAU_AR_TRANS_ERP_RCPT_T A
WHERE 1=1
AND BANK_ACC_ID IN (12036, 12050, 12035)
AND BANK_ACC_NUMBER IN ('Jhansi Cash','Dehradun Cash','Panchkula Cash')
AND RECEIPT_DATE IN (TO_DATE('9/27/2021','MM/DD/RRRR'),TO_DATE('10/22/2021','MM/DD,RRRR'),TO_DATE('11/28/2022','MM/DD/RRRR'))
GROUP BY RECEIPT_DATE, BANK_ACC_ID, BANK_ACC_NUMBER, ATTRIBUTE7, ATTRIBUTE8, RECEIPT_METHOD_ID
HAVING COUNT (1) =3)