INSERT INTO XXAU_AP_INV_H_WITH_GST_TDS_TBL
(SELECT 
   XXAU_AP_INV_H_WITH_GST_TDS_SEQ.NEXTVAL RECORD_ID
, 'XXAU_TEST_INV01' INVOICE_NUM
, NULL INVOICE_ID
, 'Standard' INVOICE_TYPE
, NULL       INVOICE_TYPE2
, NULL       LEDGER_ID
, (SELECT VENDOR_NAME FROM AP_SUPPLIERS WHERE VENDOR_ID = A.VENDOR_ID) VENDOR_NAME
, (SELECT SEGMENT1 FROM AP_SUPPLIERS WHERE VENDOR_ID = A.VENDOR_ID)     VENDOR_CODE
, NULL VENDOR_ID
, (SELECT VENDOR_SITE_CODE FROM AP_SUPPLIER_SITES_ALL WHERE VENDOR_SITE_ID = A.VENDOR_SITE_ID) VENDOR_SITE_CODE
, NULL
, SYSDATE
, SYSDATE
, A.INVOICE_CURRENCY_CODE
, A.EXCHANGE_RATE
, '124'
, '9999'
, 100
, NULL
, NULL
, NULL
, '1026-CORP_0%_Technical services'
, NULL
, A.ORG_ID
, 'N'
, ''
, -1
, SYSDATE
, -1
, SYSDATE
, 123
FROM AP_INVOICES_ALL A
WHERE ORG_ID = 288
AND CREATION_DATE > '01-JAN-2026'
AND INVOICE_ID = 5371287
AND EXISTS (SELECT 1 FROM AP_INVOICE_LINES_ALL
                    WHERE INVOICE_ID = A.INVOICE_ID
                    AND INVENTORY_ITEM_ID IS NULL))
;