INSERT INTO XXAU_AP_INV_L_WITH_GST_TDS_TBL
(SELECT 
  XXAU_AP_INV_L_WITH_GST_TDS_SEQ.NEXTVAL
, XXAU_AP_INV_H_WITH_GST_TDS_SEQ.CURRVAL
, 'XXAU_TEST_INV01'
, NULL
, NULL
, DECODE(LINE_NUMBER,1,70,2,30)
, A.DESCRIPTION
, SYSDATE --GL_DATE
, SYSDATE
, NULL
, LINE_NUMBER
, B.SEGMENT1
, B.SEGMENT3
, B.SEGMENT4
, B.SEGMENT5
, B.SEGMENT8
, B.SEGMENT9
, B.SEGMENT10
, B.SEGMENT11
, B.SEGMENT12
, B.SEGMENT13
, NULL
, '1026-CORP_0%_Technical services'
, NULL
, NULL
, NULL
, '1026-CORP_0%_Technical services'
, NULL
, 'N'
, ATTRIBUTE_CATEGORY
, 'TDS_TYPE'
, NULL
, ATTRIBUTE15
, 'XXAU_TEST_INV01' INVOICE_NUMBER
, LINE_NUMBER
, 'OFI TAX IMPORT'
, A.ORG_ID
, 'N'
, NULL
, -1
, SYSDATE
, -1
, SYSDATE
, 123
FROM AP_INVOICE_LINES_ALL A
, GL_CODE_COMBINATIONS B
WHERE 1=1
AND A.DEFAULT_DIST_CCID = B.CODE_COMBINATION_ID
AND INVOICE_ID = 5371287)

