------------------------
HEADER LEVEL
------------------------
INVOICE_NUMBER 			REQUIRED, CANNOT BE NULL
INVOICE_TYPE			REQUIRED, DEFAULT STANDARD
LEDGER_ID 				SET_OF_BOOKS_ID, REQUIRED
PARTY_NAME				TRADING_PARTNER, REQUIRED
VENDOR_SITE_CODE		VENDOR SITES, REQURIED
VENDOR_CODE				VENDOR CODE, REQUIRED
GL_DATE					GL_DATE OR SYSDATE, REQUIRED
INVOICE_DATE			INVOICE_DATE OR SYSDATE REQUIRED
INVOICE_CURRENCY_CODE	CURR_CODE REQURIED
EXCHANGE_RATE			REQUIRED
UNIT_CODE				
DEFAULT_1
INVOICE_AMOUNT
INV_ORGANIZATION_ID
LOCATION_ID
HSN_CODE
TAX_CATEGORY			
INVOICE_ID 				AP_INVOICES_INTERFACE_S.NEXTVAL



---------------------
LINE LEVEL
---------------------
INVOICE_ID			AP_INVOICE_LINES_INTERFACE_S.NEXTVAL
INVOICE_LINE_ID 	AP_INVOICES_INTERFACE_S.CURRVAL
AMOUNT				LINE_AMOUNT
DESCRIPTION			LINE_DESCRIPTION
GL_DATE				GL_DATE OR SYSDATE
INVOICE_DATE		INVOICE_DATE OR SYSDATE
LINE_NUM
GROUP_LINE_NUM,
UNIT				UNIT_NUM -- LIKE 274, 268 ETC. FOR GCC.SEGMENT1
LOCATION			SEGMENT3 -- FOR GCC.SEGMENT3
DEPARTMENT			SEGMENT4 -- FOR GCC.SEGMENT4
NATURAL_ACCOUNT		SEGMENT5 -- FOR GCC.SEGMENT5
BUSINESS_TYPE		SEGMENT8 -- FOR GCC.SEGMENT8
DEFAULT_1			SEGMENT9 -- FOR GCC.SEGMENT9
FUTURE1				SEGMENT10 -- FOR GCC.SEGMENT10
FUTURE2				SEGMENT11 -- FOR GCC.SEGMENT11
FUTURE3				SEGMENT12 -- FOR GCC.SEGMENT12
FUTURE4				SEGMENT13 -- FOR GCC.SEGMENT13
TAX_CATEGORY		
HSN_CODE	
TAX_RATE_TAX_AMOUNT,
TAX_RECOVERABLE_OR_NOT,
CONTEXT_VALUE		ATTRIBUTE_CATEGORY
INVOICE_TAX_TYPE	ATTRIBUTE10
'AP_INDUS_API'		ATTRIBUTE15
INVOICE_NUM			REFERENCE_KEY1 AILA.REFERENCE_KEY1
LINE_NUMBER			REFERENCE_KEY2 AILA.REFERENCE_KEY2
'OFI TAX IMPORT'	REFERENCE_KEY2 AILA.REFERENCE_KEY3

INVOICE_ID,
INVOICE_LINE_ID,
LINE_NUMBER,
LINE_GROUP_NUMBER,
LINE_TYPE_LOOKUP_CODE,
AMOUNT,
DESCRIPTION,
ACCOUNTING_DATE,
ORG_ID,
CREATION_DATE,
CREATED_BY,
LAST_UPDATED_BY,
LAST_UPDATE_DATE,
LAST_UPDATE_LOGIN,
DIST_CODE_COMBINATION_ID,
REFERENCE_KEY1,
REFERENCE_KEY2,
REFERENCE_KEY3,
ATTRIBUTE_CATEGORY,
ATTRIBUTE10,
ATTRIBUTE15