CREATE SEQUENCE XXAU_AP_INV_H_WITH_GST_TDS_SEQ
START WITH 1
INCREMENT BY 1
;
/

CREATE SEQUENCE XXAU_AP_INV_L_WITH_GST_TDS_SEQ
START WITH 1
INCREMENT BY 1
;
/

CREATE TABLE APPS.XXAU_AP_INV_H_WITH_GST_TDS_TBL
(
  RECORD_ID                 NUMBER,
  INVOICE_NUM               VARCHAR2(50 BYTE),
  INVOICE_ID                NUMBER,
  INVOICE_TYPE              VARCHAR2(100 BYTE),
  INVOICE_TYPE_LOOKUP_CODE  VARCHAR2(25 BYTE),
  LEDGER_ID                 NUMBER,
  VENDOR_NAME               VARCHAR2(240 BYTE),
  VENDOR_CODE               VARCHAR2(30 BYTE),
  VENDOR_ID                 NUMBER,
  VENDOR_SITE_CODE          VARCHAR2(15 BYTE),
  VENDOR_SITE_ID            NUMBER,
  GL_DATE                   DATE,
  INVOICE_DATE              DATE,
  INVOICE_CURRENCY_CODE     VARCHAR2(10 BYTE),
  EXCHANGE_RATE             NUMBER,
  UNIT_CODE                 VARCHAR2(100 BYTE),
  DEFAULT_1                 VARCHAR2(100 BYTE),
  INVOICE_AMOUNT            NUMBER,
  INV_ORGANIZATION_ID       NUMBER,
  LOCATION_ID               NUMBER,
  HSN_CODE                  VARCHAR2(400 BYTE),
  TAX_CATEGORY              VARCHAR2(1000 BYTE),
  ERP_TAX_CATEGORY_ID       NUMBER,
  ORGANIZATION_NAME         VARCHAR2(240 BYTE),
  SHORT_CODE                VARCHAR2(150 BYTE),
  ERP_ORG_ID                NUMBER,
  ACCTS_PAY_CC_ID           NUMBER,
  PROCESS_FLAG              VARCHAR2(10 BYTE),
  ERROR_MSG                 VARCHAR2(4000 BYTE),
  CREATED_BY                NUMBER,
  CREATION_DATE             DATE,
  UPDATED_BY                NUMBER,
  LAST_UPDATE_DATE          DATE,
  BATCH_ID                  NUMBER
);

/

CREATE TABLE XXAU_AP_INV_L_WITH_GST_TDS_TBL
(	RECORD_ID                   NUMBER,
  H_RECORD_ID                 NUMBER,
  INVOICE_NUM                 VARCHAR2(50 BYTE),
  ERP_INVOICE_ID              NUMBER,
  ERP_INVOICE_LINE_ID         NUMBER,
  LINE_AMOUNT                 NUMBER,
  LINE_DESCRIPTION            VARCHAR2(240 BYTE),
  GL_DATE                     DATE,
  INVOICE_DATE                DATE,
  ERP_LINE_NUM                NUMBER,
  GROUP_LINE_NUM              NUMBER,
  UNIT                        VARCHAR2(100 BYTE),
  LOCATION                    VARCHAR2(100 BYTE),
  DEPARTMENT                  VARCHAR2(100 BYTE),
  NATURAL_ACCOUNT             VARCHAR2(100 BYTE),
  BUSINESS_TYPE               VARCHAR2(100 BYTE),
  DEFAULT_1                   VARCHAR2(100 BYTE),
  FUTURE1                     VARCHAR2(100 BYTE),
  FUTURE2                     VARCHAR2(100 BYTE),
  FUTURE3                     VARCHAR2(100 BYTE),
  FUTURE4                     VARCHAR2(100 BYTE),
  LINE_TYPE                   VARCHAR2(80 BYTE),
  ERP_LINE_TYPE_CODE          VARCHAR2(30 BYTE),
  ERP_CCID                    NUMBER,
  TAX_CATEGORY                VARCHAR2(1000 BYTE),
  TAX_CATEGORY_ID             NUMBER,
  HSN_CODE                    VARCHAR2(1000 BYTE),
  TAX_RATE_TAX_AMOUNT         NUMBER,
  TAX_RATE_NAME               VARCHAR2(240 BYTE),
  ERP_TAX_RATE_ID             NUMBER,
  TAX_RECOVERABLE_OR_NOT      VARCHAR2(10 BYTE),
  CONTEXT_VALUE               VARCHAR2(1000 BYTE),
  INVOICE_TAX_TYPE            VARCHAR2(1000 BYTE),
  ERP_TAX_TYPE_ID             VARCHAR2(1000 BYTE),
  FLEX_VALUE_MEANING          VARCHAR2(150 BYTE),
  ATTRIBUTE10                 VARCHAR2(150 BYTE),
  ATTRIBUTE15                 VARCHAR2(150 BYTE),
  REFERENCE_KEY1_INVOICE_NUM  VARCHAR2(50 BYTE),
  REFERENCE_KEY2_LINE_NUM     VARCHAR2(150 BYTE),
  REFERENCE_KEY3              VARCHAR2(150 BYTE),
  ORGANIZATION_NAME           VARCHAR2(240 BYTE),
  SHORT_CODE                  VARCHAR2(150 BYTE),
  ERP_ORG_ID                  NUMBER,
  PROCESS_FLAG                VARCHAR2(10 BYTE),
  ERROR_MSG                   VARCHAR2(4000 BYTE),
  CREATED_BY                  NUMBER,
  CREATION_DATE               DATE,
  UPDATED_BY                  NUMBER,
  LAST_UPDATE_DATE            DATE,
  BATCH_ID                    NUMBER
);