PROCEDURE CREATE_CUST_ACCOUNT (    P_ORGANIZATION_NAME IN VARCHAR2
								,  P_ACCOUNT_NAME IN VARCHAR2
								,  P_ABC_TYPE IN VARCHAR2
								,  P_AGENCY_ID IN NUMBER
								,  P_CUSTOMER_TYPE IN VARCHAR2
								,  P_CUSTOMER_CLASS_CODE IN VARCHAR2
								,  P_UNIT IN VARCHAR2
								,  P_PARTY_ID IN OUT NUMBER
								,  P_CUST_ACCOUNT_ID OUT NUMBER
								,  P_PARTY_NUMBER OUT VARCHAR2
								,  P_PROFILE_ID OUT NUMBER
								,  P_ACCOUNT_NUMBER OUT VARCHAR2
								,  P_MSG OUT VARCHAR2
								)
AS
    CUSTACCCOUNTREC              HZ_CUST_ACCOUNT_V2PUB.CUST_ACCOUNT_REC_TYPE;
    CUSTPROFILEREC               HZ_CUSTOMER_PROFILE_V2PUB.CUSTOMER_PROFILE_REC_TYPE;
    CUSTORGREC                   HZ_PARTY_V2PUB.ORGANIZATION_REC_TYPE;
    CUSTPARTYREC                 HZ_PARTY_V2PUB.PARTY_REC_TYPE;
	
	LC_PARTY_NUMBER HZ_PARTIES.PARTY_NUMBER%TYPE;
	X_RETURN_STATUS VARCHAR2(100);
	X_MSG_COUNT NUMBER;
	X_MSG_DATA VARCHAR2(4000);
BEGIN
	x_account_number := NULL;
	x_party_id := NULL;
	x_cust_account_id := NULL;

	CUSTACCCOUNTREC.ACCOUNT_NAME := P_ACCOUNT_NAME; --CREATE_CUSTOMER_REC.ACCOUNT_DESCRIPTION; -- CURSOR CREATE_CUST
	CUSTACCCOUNTREC.ATTRIBUTE19  :=  P_AGENCY_ID ; --CREATE_CUSTOMER_REC.AGENCY_ID;
	CUSTACCCOUNTREC.ATTRIBUTE20  := TO_CHAR(SYSDATE, 'DD-MON-YYYY HH24:MI:SS');
	CUSTACCCOUNTREC.ATTRIBUTE10  := P_ABC_TYPE ; --CREATE_CUSTOMER_REC.ABC_TYPE;
	CUSTACCCOUNTREC.STATUS := 'A';
	CUSTACCCOUNTREC.ATTRIBUTE_CATEGORY := P_CUSTOMER_TYPE; --CREATE_CUSTOMER_REC.CUSTOMER_TYPE;
	CUSTACCCOUNTREC.CUSTOMER_TYPE := 'R';
	CUSTACCCOUNTREC.CUSTOMER_CLASS_CODE := P_CUSTOMER_CLASS_CODE ; --CREATE_CUSTOMER_REC.CUSTOMER_CLASS_CODE;
	CUSTACCCOUNTREC.CREATED_BY_MODULE := 'BO_API';

	CUSTPARTYREC.STATUS := 'A';
	CUSTORGREC.ORGANIZATION_NAME := P_ORGANIZATION_NAME; --CREATE_CUSTOMER_REC.CUSTOMER_NAME;
	CUSTORGREC.PARTY_REC.ATTRIBUTE_CATEGORY := P_CUSTOMER_TYPE; --CREATE_CUSTOMER_REC.CUSTOMER_TYPE;
	CUSTORGREC.PARTY_REC.STATUS := 'A';
	CUSTORGREC.PARTY_REC.ATTRIBUTE20 := P_UNIT; --MAIN_UNIT1.UNIT; -- CURSOR MAIN_UNIT
	CUSTORGREC.PARTY_REC.ATTRIBUTE19 := CREATE_CUSTOMER_REC.ACCOUNT_DESCRIPTION;
	CUSTORGREC.CREATED_BY_MODULE := 'BO_API';
	CUSTORGREC.PARTY_REC := CUSTPARTYREC;
/*API to create customer account, party and customer profile*/
	HZ_CUST_ACCOUNT_V2PUB.CREATE_CUST_ACCOUNT(
		P_INIT_MSG_LIST        => 'T',
		P_CUST_ACCOUNT_REC     => CUSTACCCOUNTREC,
		P_ORGANIZATION_REC     => CUSTORGREC,
		P_CUSTOMER_PROFILE_REC => CUSTPROFILEREC,
		P_CREATE_PROFILE_AMT   => 'F',
		X_CUST_ACCOUNT_ID      => P_CUST_ACCOUNT_ID,
		X_ACCOUNT_NUMBER       => P_ACCOUNT_NUMBER,
		X_PARTY_ID             => P_PARTY_ID,
		X_PARTY_NUMBER         => LC_PARTY_NUMBER,
		X_PROFILE_ID           => P_PROFILE_ID,
		X_RETURN_STATUS        => X_RETURN_STATUS,
		X_MSG_COUNT            => X_MSG_COUNT,
		X_MSG_DATA             => X_MSG_DATA
	);

	IF X_RETURN_STATUS = 'S' THEN
		FND_FILE.PUT_LINE(FND_FILE.LOG, 'Creation of Party of Type Organization and customer account is Successful'		);
		FND_FILE.PUT_LINE(FND_FILE.LOG, 'x_cust_account_id :' || P_CUST_ACCOUNT_ID);
		FND_FILE.PUT_LINE(FND_FILE.LOG, 'x_account_number :' || P_ACCOUNT_NUMBER);
		FND_FILE.PUT_LINE(FND_FILE.LOG, 'x_party_id :' || P_PARTY_ID);
		lv_party_id := x_party_id;
		FND_FILE.PUT_LINE(FND_FILE.LOG, 'x_party_number :' || LC_PARTY_NUMBER);
		FND_FILE.PUT_LINE(FND_FILE.LOG, 'x_profile_id :' || P_PROFILE_ID);
		COMMIT;
	ELSE
		FND_FILE.PUT_LINE(FND_FILE.LOG, 'Creation of Party of Type Organization and customer account failed:' || x_msg_data		);
		FOR i IN 1 .. l_msg_count
		  LOOP
			 l_msg_data := FND_MSG_PUB.get( p_msg_index => i, p_encoded => 'F');
			 FND_FILE.PUT_LINE(FND_FILE.LOG, i|| ') '|| l_msg_data);
			 P_MSG := P_MSG||l_msg_data||'; ';
		  END LOOP;
		  ROLLBACK;
		  P_CUST_ACCOUNT_ID:= -1;
		ROLLBACK;
	END IF;
EXCEPTION
	WHEN OTHERS 
	THEN 
		FND_FILE.PUT_LINE(FND_FILE.LOG,SQLCODE||' - '||SQLERRM);
		P_CUST_ACCOUNT_ID := -1;
END CREATE_CUST_ACCOUNT;