PROCEDURE CREATE_CUST_ACCT_SITE (P_CUST_ACCOUNT_ID IN NUMBER
								,P_PARTY_SITE_ID IN NUMBER
								,P_CUSTOMER_TYPE IN VARCHAR2
								,P_CUST_ACCT_SITE_ID OUT NUMBER
								,P_MSG OUT VARCHAR2
								)
AS
	L_CUST_ACCT_SITE_REC HZ_CUST_ACCOUNT_SITE_V2PUB.CUST_ACCT_SITE_REC_TYPE;
	L_CUST_ACCT_SITE_ID  HZ_CUST_ACCT_SITES.CUST_ACCT_SITE_ID%TYPE;
	L_RETURN_STATUS      VARCHAR2(100);
	L_MSG_COUNT          NUMBER;
	L_MSG_DATA           VARCHAR2(2000);
BEGIN
	DBMS_OUTPUT.ENABLE (buffer_size => NULL);
	P_MSG:= NULL;
	FND_FILE.PUT_LINE(FND_FILE.LOG,RPAD('-',25,'-'));
	--Initiate the EBS Environment for API processing
	FND_GLOBAL.APPS_INITIALIZE(GN_USER_ID, GN_RESP_ID, GN_RESP_APPL_ID);
	MO_GLOBAL.INIT('AR');
	FND_CLIENT_INFO.SET_ORG_CONTEXT(GN_ORG_ID);
	
	L_CUST_ACCT_SITE_REC.CUST_ACCOUNT_ID := P_CUST_ACCOUNT_ID;
	L_CUST_ACCT_SITE_REC.PARTY_SITE_ID := P_PARTY_SITE_ID;
	L_CUST_ACCT_SITE_REC.CREATED_BY_MODULE := 'BO_API';
	L_CUST_ACCT_SITE_REC.ATTRIBUTE_CATEGORY := P_CUSTOMER_TYPE; --CREATE_CUSTOMER_REC.CUSTOMER_TYPE;
	L_CUST_ACCT_SITE_REC.ORG_ID := 288;

	HZ_CUST_ACCOUNT_SITE_V2PUB.CREATE_CUST_ACCT_SITE
												   (	P_INIT_MSG_LIST      => FND_API.G_TRUE,
														P_CUST_ACCT_SITE_REC => L_CUST_ACCT_SITE_REC,
														X_CUST_ACCT_SITE_ID  => L_CUST_ACCT_SITE_ID,
														X_RETURN_STATUS      => L_RETURN_STATUS,
														X_MSG_COUNT          => L_MSG_COUNT,
														X_MSG_DATA           => L_MSG_DATA
													);
		   IF L_RETURN_STATUS = 'S' 
		   THEN
			  FND_FILE.PUT_LINE(FND_FILE.LOG,'Cust Acct Site Creation is Successful '); 
			  FND_FILE.PUT_LINE(FND_FILE.LOG,'Cust Acct Site Id = '||l_cust_acct_site_id); 
			  COMMIT;
		   ELSE
			  FOR i IN 1 .. l_msg_count
			  LOOP
				 l_msg_data := FND_MSG_PUB.get( p_msg_index => i, p_encoded => 'F');
				 FND_FILE.PUT_LINE(FND_FILE.LOG, i|| ') '|| l_msg_data);
				 P_MSG := P_MSG||l_msg_data||'; ';
			  END LOOP;
			  ROLLBACK;
			  L_CUST_ACCT_SITE_ID:=-1;
			  --FND_FILE.PUT_LINE(FND_FILE.LOG,'Cust Acct Site Creation failed:'||l_msg_data);
		   END IF;
		   --FND_FILE.PUT_LINE(FND_FILE.LOG,'Cust Acct Site Creation Complete');
		P_CUST_ACCT_SITE_ID:= L_CUST_ACCT_SITE_ID;
EXCEPTION
	WHEN OTHERS 
	THEN 
		FND_FILE.PUT_LINE(FND_FILE.LOG,SQLCODE||' - '||SQLERRM);
		P_CUST_ACCT_SITE_ID := -1;
END CREATE_CUST_ACCT_SITE;