PROCEDURE CREATE_LOCATION (	   P_ADDRESS1 IN VARCHAR2
							,  P_ADDRESS2 IN VARCHAR2
							,  P_ADDRESS3 IN VARCHAR2
							,  P_ADDRESS4 IN VARCHAR2
							,  P_CITY  IN VARCHAR2
							,  P_POSTAL_CODE IN NUMBER
							,  P_STATE IN VARCHAR2
							,  P_COUNTY IN VARCHAR2
							,  P_COUNTRY IN VARCHAR2
							,  P_LOCATION1 IN VARCHAR2
							,  P_LOCATION_ID OUT NUMBER
							,  P_MSG OUT VARCHAR2)
IS
	L_LOCATION_REC              HZ_LOCATION_V2PUB.LOCATION_REC_TYPE;
	X_RETURN_STATUS				VARCHAR2(100);
	X_MSG_COUNT					NUMBER;
	X_MSG_DATA					varchar2(4000);
	L_MSG_DATA					varchar2(4000);
BEGIN
	P_MSG := NULL;
	FND_FILE.PUT_LINE(FND_FILE.LOG,RPAD('-',25,'-'));
	   --INITIATE THE EBS ENVIRONMENT FOR API PROCESSING
	FND_GLOBAL.APPS_INITIALIZE(GN_USER_ID, GN_RESP_ID, GN_RESP_APPL_ID);
	MO_GLOBAL.INIT('AR');
	FND_CLIENT_INFO.SET_ORG_CONTEXT(GN_ORG_ID);

	L_LOCATION_REC.ADDRESS1 := P_ADDRESS1; --CREATE_SITE_REC.ADDRESS1;
	L_LOCATION_REC.ADDRESS2 := P_ADDRESS2; --CREATE_SITE_REC.ADDRESS2;
	L_LOCATION_REC.ADDRESS3 := P_ADDRESS3; --CREATE_SITE_REC.ADDRESS3;
	L_LOCATION_REC.ADDRESS4 := P_ADDRESS4; --CREATE_SITE_REC.ADDRESS4;
	L_LOCATION_REC.CITY 	:= P_CITY; --CREATE_SITE_REC.CITY;
	L_LOCATION_REC.POSTAL_CODE := P_POSTAL_CODE; --CREATE_SITE_REC.POSTAL_CODE;
	L_LOCATION_REC.STATE := P_STATE; --CREATE_SITE_REC.STATE;
	L_LOCATION_REC.COUNTRY := P_COUNTRY; --CREATE_SITE_REC.COUNTRY;
	L_LOCATION_REC.CREATED_BY_MODULE := 'TCA_V2_API';
	L_LOCATION_REC.DESCRIPTION := P_LOCATION1; --CREATE_SITE_REC.LOCATION1;
	L_LOCATION_REC.COUNTY := P_COUNTY; --CREATE_SITE_REC.COUNTY;
	HZ_LOCATION_V2PUB.CREATE_LOCATION(
										P_INIT_MSG_LIST => FND_API.G_TRUE,
										P_LOCATION_REC  => L_LOCATION_REC,
										X_LOCATION_ID   => P_LOCATION_ID,
										X_RETURN_STATUS => X_RETURN_STATUS,
										X_MSG_COUNT     => X_MSG_COUNT,
										X_MSG_DATA      => X_MSG_DATA
									);

	FND_FILE.PUT_LINE(FND_FILE.LOG, 'API Status      :- ' || x_return_status);
	IF X_RETURN_STATUS <> 'S' THEN
		FND_FILE.PUT_LINE(FND_FILE.LOG,'Location Creation is Successful '); 
		FND_FILE.PUT_LINE(FND_FILE.LOG,'Location Id = '||P_LOCATION_ID); 
		COMMIT;
	ELSE
		FOR i IN 1 .. X_MSG_COUNT
			LOOP
				L_MSG_DATA := FND_MSG_PUB.GET( P_MSG_INDEX => I, P_ENCODED => 'F');
				FND_FILE.PUT_LINE(FND_FILE.LOG, I|| ') '|| L_MSG_DATA);
				P_MSG := P_MSG || L_MSG_DATA||'; ';
			END LOOP;
		ROLLBACK;
		P_LOCATION_ID:=-1;
	END IF;
EXCEPTION
	WHEN OTHERS 
	THEN 
		P_LOCATION_ID := -1;
		FND_FILE.PUT_LINE(FND_FILE.LOG,SQLCODE||' - '||SQLERRM);
END CREATE_LOCATION;