PROCEDURE CREATE_CUST_SITE_USES (P_CUST_ACCT_SITE_ID IN NUMBER
								,P_SITE_USE_CODE IN VARCHAR2
								,P_CUSTOMER_TYPE IN VARCHAR2
								,P_LOCATION IN VARCHAR2
								,P_CENTRE_NUMBER IN VARCHAR2
								,P_PRIMARY_FLAG IN VARCHAR2
								,P_PAYMENT_TERMS IN VARCHAR2
								,P_REC_ACCOUNT IN VARCHAR2
								,P_SITE_USE_ID OUT NUMBER
								,P_MSG OUT VARCHAR2
								) 
AS
	L_CUST_SITE_USE_REC    	HZ_CUST_ACCOUNT_SITE_V2PUB.CUST_SITE_USE_REC_TYPE;
	L_CUSTOMER_PROFILE_REC 	HZ_CUSTOMER_PROFILE_V2PUB.CUSTOMER_PROFILE_REC_TYPE;
	L_SITE_USE_ID          	HZ_CUST_SITE_USES.SITE_USE_ID%TYPE;
	L_RETURN_STATUS        	VARCHAR2(100);
	L_MSG_COUNT            	NUMBER;
	L_MSG_DATA             	VARCHAR2(2000);
	LN_TERM_ID				NUMBER;
	LN_GL_CODE_ID			NUMBER;
	LN_ID_FLEX_NUM			NUMBER;
	LC_STATUS             	VARCHAR2(2000);
BEGIN

		-- PAYMENT TERMS
		LN_TERM_ID := NULL;
		IF P_PAYMENT_TERMS IS NOT NULL THEN
			BEGIN
				SELECT TERM_ID
				INTO LN_TERM_ID
				FROM
					APPS.RA_TERMS
				WHERE
					UPPER(NAME) = TRIM(P_PAYMENT_TERMS); --CREATE_SITE_REC.PAYMENT_TERMS;

			EXCEPTION
				WHEN NO_DATA_FOUND THEN
					LN_TERM_ID := NULL;
				WHEN OTHERS THEN
					LN_TERM_ID := NULL;
			END;
		END IF;
		
		-- CODE COMBINATIONS
		BEGIN
			SELECT
				CODE_COMBINATION_ID
			INTO LN_GL_CODE_ID
			FROM
				APPS.GL_CODE_COMBINATIONS_KFV X
			WHERE
				X.CONCATENATED_SEGMENTS = P_REC_ACCOUNT; --CREATE_SITE_REC.REC_ACCOUNT;

		EXCEPTION
			WHEN OTHERS THEN
				BEGIN
					BEGIN
						SELECT ID_FLEX_NUM
						INTO LN_ID_FLEX_NUM
						FROM
							APPS.FND_ID_FLEX_STRUCTURES
						WHERE
								ID_FLEX_CODE = 'GL#'
							AND ID_FLEX_STRUCTURE_CODE = 'AUPL_CHART_OF_ACCOUNT';

					EXCEPTION
						WHEN OTHERS THEN
							LN_ID_FLEX_NUM := NULL;
					END;

					LC_STATUS := FND_FLEX_KEYVAL.VALIDATE_SEGS('CREATE_COMBINATION'
																, 'SQLGL'
																, 'GL#'
																, LN_ID_FLEX_NUM
																, P_REC_ACCOUNT --CREATE_SITE_REC.REC_ACCOUNT
																, 'V'
																, SYSDATE
																, 'ALL' , NULL, NULL, NULL, NULL, FALSE, FALSE, NULL,NULL, NULL
																);
																
					BEGIN
						SELECT CODE_COMBINATION_ID
						INTO LN_GL_CODE_ID
						FROM
							GL_CODE_COMBINATIONS_KFV A
						WHERE
							CONCATENATED_SEGMENTS = P_REC_ACCOUNT --CREATE_SITE_REC.REC_ACCOUNT;
						;

					EXCEPTION
						WHEN OTHERS THEN
							LN_GL_CODE_ID := 0;
					END;
				END;
		END;
		
		
		MO_GLOBAL.SET_POLICY_CONTEXT('S', 288);
		L_CUST_SITE_USE_REC.SITE_USE_CODE := P_SITE_USE_CODE;
		L_CUST_SITE_USE_REC.ATTRIBUTE_CATEGORY := P_CUSTOMER_TYPE; --CREATE_CUSTOMER_REC.CUSTOMER_TYPE;
		L_CUST_SITE_USE_REC.CUST_ACCT_SITE_ID := P_CUST_ACCT_SITE_ID;
		L_CUST_SITE_USE_REC.CREATED_BY_MODULE := 'BO_API';
		L_CUST_SITE_USE_REC.ORG_ID := 288;
		L_CUST_SITE_USE_REC.PRIMARY_FLAG := P_PRIMARY_FLAG; --CREATE_SITE_REC.PRIMARY_FLAG;
		L_CUST_SITE_USE_REC.LOCATION := P_LOCATION; --CREATE_SITE_REC.LOCATION1;
		L_CUSTOMER_PROFILE_REC.STANDARD_TERMS := LN_TERM_ID;
		L_CUST_SITE_USE_REC.ATTRIBUTE25 := P_CENTRE_NUMBER; --CREATE_SITE_REC.CENTRE_NUMBER;
  
		L_CUST_SITE_USE_REC.GL_ID_REC := LN_GL_CODE_ID;

		HZ_CUST_ACCOUNT_SITE_V2PUB.CREATE_CUST_SITE_USE
						   (
							 P_INIT_MSG_LIST         => FND_API.G_TRUE,
							 P_CUST_SITE_USE_REC     => L_CUST_SITE_USE_REC,
							 P_CUSTOMER_PROFILE_REC  => L_CUSTOMER_PROFILE_REC,
							 P_CREATE_PROFILE        => FND_API.G_TRUE,
							 P_CREATE_PROFILE_AMT    => FND_API.G_TRUE,
							 X_SITE_USE_ID           => L_SITE_USE_ID,
							 X_RETURN_STATUS         => L_RETURN_STATUS,
							 X_MSG_COUNT             => L_MSG_COUNT,
							 X_MSG_DATA              => L_MSG_DATA
							);
							
		   IF L_RETURN_STATUS = 'S' 
		   THEN
				FND_FILE.PUT_LINE(FND_FILE.LOG,'Cust Site Use Creation is Successful '); 
				FND_FILE.PUT_LINE(FND_FILE.LOG,'site_use_id = '||L_SITE_USE_ID); 
				COMMIT;
		   ELSE
				--FND_FILE.PUT_LINE(FND_FILE.LOG,'Cust Site Use Creation failed:'||l_msg_data);
				FOR i IN 1 .. L_MSG_COUNT
				LOOP
					 l_msg_data := FND_MSG_PUB.get( p_msg_index => i, p_encoded => 'F');
					 FND_FILE.PUT_LINE(FND_FILE.LOG, i|| ') '|| l_msg_data);
					 P_MSG := P_MSG||l_msg_data||'; ';
				END LOOP;
				
				-- STATE - Added on 07-APR-2026, to assign the already exists site use id
				BEGIN
					SELECT SITE_USE_ID
					INTO L_SITE_USE_ID
					FROM HZ_CUST_SITE_USES_ALL
					WHERE 1=1
					AND UPPER(P_MSG) LIKE '%LOCATION ALREADY EXISTS FOR THIS BUSINESS PURPOSE AND CUSTOMER%'
					AND LOCATION = P_LOCATION
					AND SITE_USE_CODE = 'SHIP_TO'
					AND EXISTS (SELECT 1
								FROM HZ_CUST_ACCOUNTS HCA
								, HZ_CUST_ACCT_SITES_ALL HCASA
								WHERE 1=1
								AND HCA.CUST_ACCOUNT_ID = HCASA.CUST_ACCOUNT_ID
								AND HCASA.CUST_ACCT_SITE_ID = P_CUST_ACCT_SITE_ID);
					COMMIT;
				EXCEPTION
				WHEN OTHERS THEN
					ROLLBACK;
					L_SITE_USE_ID:= -1;
				END;
		   END IF;
		P_SITE_USE_ID := L_SITE_USE_ID;
EXCEPTION
WHEN OTHERS 
THEN 
	FND_FILE.PUT_LINE(FND_FILE.LOG,SQLCODE||' - '||SQLERRM);
	P_SITE_USE_ID := -1;
END CREATE_CUST_SITE_USES;