PROCEDURE CREATE_PARTY_SITE ( P_PARTY_ID IN NUMBER
							, P_LOCATION_ID IN NUMBER
							, P_CUSTOMER_TYPE IN VARCHAR2
							, P_STATION_NAME IN VARCHAR2
							, P_PARTY_SITE_ID OUT NUMBER
							, P_PARTY_SITE_NUM OUT VARCHAR2
							, P_MSG OUT VARCHAR2) 
AS

	P_MSG := NULL;
	FND_FILE.PUT_LINE(FND_FILE.LOG,RPAD('-',25,'-'));
	--Initiate the EBS Environment for API processing
	FND_GLOBAL.APPS_INITIALIZE(GN_USER_ID, GN_RESP_ID, GN_RESP_APPL_ID);
	MO_GLOBAL.INIT('AR');
	FND_CLIENT_INFO.SET_ORG_CONTEXT(GN_ORG_ID);
	
	L_PARTY_SITE_REC    HZ_PARTY_SITE_V2PUB.PARTY_SITE_REC_TYPE;
	L_PARTY_SITE_ID     HZ_PARTY_SITES.PARTY_SITE_ID%TYPE;
	L_PARTY_SITE_NUMBER HZ_PARTY_SITES.PARTY_SITE_NUMBER%TYPE;
	L_RETURN_STATUS     VARCHAR2(100);
	L_MSG_COUNT         NUMBER;
	L_MSG_DATA          VARCHAR2(2000);
BEGIN
	L_PARTY_SITE_REC.PARTY_ID := P_PARTY_ID;
	L_PARTY_SITE_REC.LOCATION_ID := P_LOCATION_ID;

	L_PARTY_SITE_REC.STATUS := 'A';
	L_PARTY_SITE_REC.ATTRIBUTE_CATEGORY := P_CUSTOMER_TYPE; --CREATE_CUSTOMER_REC.CUSTOMER_TYPE;
	L_PARTY_SITE_REC.PARTY_SITE_NAME := P_STATION_NAME; --CREATE_SITE_REC.STATION_NAME;
	L_PARTY_SITE_REC.CREATED_BY_MODULE := 'TCA_V2_API';

	HZ_PARTY_SITE_V2PUB.CREATE_PARTY_SITE
										(
										 P_INIT_MSG_LIST     => FND_API.G_TRUE,
										 P_PARTY_SITE_REC    => L_PARTY_SITE_REC,
										 X_PARTY_SITE_ID     => L_PARTY_SITE_ID,
										 X_PARTY_SITE_NUMBER => L_PARTY_SITE_NUMBER,
										 X_RETURN_STATUS     => L_RETURN_STATUS,
										 X_MSG_COUNT         => L_MSG_COUNT,
										 X_MSG_DATA          => L_MSG_DATA
										);

	FND_FILE.PUT_LINE(FND_FILE.LOG, 'API Status      :- ' || L_RETURN_STATUS);
	IF L_RETURN_STATUS = 'S' 
	   THEN
			FND_FILE.PUT_LINE(FND_FILE.LOG,'Party Site Creation is Successful '); 
			FND_FILE.PUT_LINE(FND_FILE.LOG,'Party Site Number = '||L_PARTY_SITE_NUMBER); 
			FND_FILE.PUT_LINE(FND_FILE.LOG,'Party Site Id = '||L_PARTY_SITE_ID); 
			COMMIT;
	   ELSE
		  FOR i IN 1 .. L_MSG_COUNT
		  LOOP
			 l_msg_data := FND_MSG_PUB.get( p_msg_index => i, p_encoded => 'F');
			 FND_FILE.PUT_LINE(FND_FILE.LOG, i|| ') '|| l_msg_data);
			 P_MSG := P_MSG||l_msg_data||'; ';
		  END LOOP;
		  ROLLBACK;
		  L_PARTY_SITE_ID:=-1;
	   END IF;
	P_PARTY_SITE_ID:=L_PARTY_SITE_ID;
EXCEPTION
WHEN OTHERS 
THEN 
	FND_FILE.PUT_LINE(FND_FILE.LOG,SQLCODE||' - '||SQLERRM);
	P_PARTY_SITE_ID := -1;
END CREATE_PARTY_SITE;