CREATE OR REPLACE PACKAGE XXAU_UPDT_CUSTOM_CUST_DATA_PKG
AS
	PROCEDURE UPDATE_CUST_DETAILS;

	PROCEDURE UPDT_CUST_WITH_SITES_MAST_NEW (P_CUST_ACCOUNT_ID IN NUMBER,
											P_ACCOUNT_NUMBER IN VARCHAR2,
											P_PARTY_ID IN NUMBER,
											P_PROCESS_FLAG IN VARCHAR2,
											P_ERR_MSG IN VARCHAR2,
											P_AGENCY_ID IN NUMBER
											);
	
	PROCEDURE UPDATE_CUSTS_MAST_NEW (P_PROCESS_FLAG IN VARCHAR2,
								P_ERR_MSG IN VARCHAR2,
								P_AGENCY_ID IN NUMBER
								);
	
	PROCEDURE UPDATE_CUSTS_SHIP_SITES (P_ACCOUNT_NUMBER IN VARCHAR2, 
									P_CUST_ACCT_SITE_ID IN NUMBER,
									P_SITE_USE_ID IN NUMBER,
									P_CUST_ACCOUNT_ID IN NUMBER,
									P_PARTY_ID IN NUMBER,
									P_PROCESS_FLAG IN VARCHAR2,
									P_CCID IN NUMBER,
									P_ERR_MSG IN VARCHAR2,
									P_AGENCY_ID IN NUMBER,
									P_CENTRE_NUMBER IN VARCHAR2,
									P_MAIN_CENTRE_NUMBER IN VARCHAR2
									);
	PROCEDURE VALIDATE_REQUIRED;
	PROCEDURE LOAD_DATA;

END XXAU_UPDT_CUSTOM_CUST_DATA_PKG;