SELECT                              
  INVOICE_ID
, INVOICE_NUM
, SET_OF_BOOKS_ID
, INVOICE_CURRENCY_CODE
, PAYMENT_CURRENCY_CODE
, PAYMENT_CROSS_RATE
, INVOICE_AMOUNT
, VENDOR_ID
, VENDOR_SITE_ID
, DISCOUNT_AMOUNT_TAKEN
, AMOUNT_PAID
, INVOICE_DATE
, SOURCE 
, INVOICE_TYPE_LOOKUP_CODE
, APPROVAL_READY_FLAG
, AMOUNT_APPLICABLE_TO_DISCOUNT
, TERMS_ID
, TERMS_DATE             -- THIS IS THE DATE FROM WHICH THE 10, 15, 30,45 OR 90 DAYS  WILL BE COUNTED
, ACCTS_PAY_CODE_COMBINATION_ID     -- IT CONTAINS THE CREADIT ACCOUNT AS LIBALITY ACCOUNT
, CREATION_DATE
, PAYMENT_STATUS_FLAG
, PAYMENT_METHOD_CODE
, PARTY_ID
, PARTY_SITE_ID
, EXTERNAL_BANK_ACCOUNT_ID
, a.*
FROM AP_INVOICES_ALL A
WHERE INVOICE_NUM = '1113AK'

/*

After validating the AP Invoice we can directly make the payments whereas accounting can be done directly after validation or can be done after making payments.


----- Create Accounting have 3 Types/Modes ------
Draft      : Create the sample accounting not the original  and these type of accountings cannot be transfer to GL
Final      : Create the Real Accounting Entries and won't transffer to GL -- we have to manually run the program -- 'Create Accounting'
Final Post : Create the Real Accounting Entries and Transffers to GL and then POST Automatically. It will update the Balances in the Respective Creadit and Debit Accounts -- Automatically fires the program -> 'Create Accounting'

*/

--UPDATE AP_INVOICES_ALL
--SET APPROVAL_READY_FLAG = 'Y'
--WHERE INVOICE_ID = 1120836

SELECT * --source_trx_id , SOURCE_TRX_LEVEL_TYPE
FROM AP_INVOICE_LINES_ALL
WHERE INVOICE_ID = 1120838 -- 1120837 --1120836

SELECT INVOICE_DISTRIBUTION_ID                      -- IT CONTAINS THE DEBIT ACCOUNT DETAILS
, ACCOUNTING_DATE
, ACCOUNTING_EVENT_ID
, INVOICE_LINE_NUMBER
, DISTRIBUTION_LINE_NUMBER
, INVOICE_ID
, DIST_CODE_COMBINATION_ID 
, LINE_TYPE_LOOKUP_CODE
, AMOUNT
, a.*
FROM AP_INVOICE_DISTRIBUTIONS_ALL a
WHERE 1=1
--AND INVOICE_LINE_NUMBER = 1
AND INVOICE_ID = 1120838 --1120837 --1120836



SELECT CODE_COMBINATION_ID
, CHART_OF_ACCOUNTS_ID
, SEGMENT1||'.'||SEGMENT2||'.'||SEGMENT3||'.'||SEGMENT4||'.'||SEGMENT5||'.'||SEGMENT6||'.'||SEGMENT7||'.'||SEGMENT8 CODE_COMBINATION
FROM GL_CODE_COMBINATIONS
WHERE CODE_COMBINATION_ID IN ( 493811, 775846 ,515713)


SELECT *
FROM AP_PAYMENT_SCHEDULES_ALL
WHERE 1=1
AND INVOICE_ID = 1120838 --1120837 --1120836

SELECT *
FROM AP_INVOICE_PAYMENTS_ALL
WHERE 1=1
AND INVOICE_ID = 1120838 --1120837 --1120836

SELECT *
FROM AP_CHECKS_ALL
WHERE 1=1
AND CHECK_ID = 499046

SELECT *
FROM XLA_TRANSACTION_ENTITIES
WHERE 1=1
--AND SOURCE_ID_INT_1 = 1120837 --1120836


SELECT *
FROM XLA_EVENTS
WHERE EVENT_ID = 4561493 --4561489 --4561488


SELECT *
FROM XLA_AE_HEADERS
WHERE 1=1
AND ENTITY_ID = 4102159 --4102155 --4102154
ORDER BY AE_HEADER_ID DESC

SELECT *
FROM XLA_AE_LINES
WHERE AE_HEADER_ID = 55939436 --55939433 --55939432

SELECT *
FROM GL_IMPORT_REFERENCES                 --SUBLEDGER_DOC_SEQUENCE_ID : 3749 ,  SUBLEDGER_DOC_SEQUENCE_VALUE: 842625396
WHERE 1=1
AND GL_SL_LINK_ID IN (SELECT GL_SL_LINK_ID
FROM XLA_AE_LINES
WHERE AE_HEADER_ID = 55939433)



SELECT *
FROM GL_JE_HEADERS
WHERE 1=1
AND JE_HEADER_ID = 3849823

SELECT *
FROM GL_JE_LINES
WHERE 1=1
AND JE_HEADER_ID = 3849823

SELECT *
FROM GL_JE_BATCHES
WHERE 1=1
AND JE_BATCH_ID = 792223


SELECT *
FROM GL_BALANCES
WHERE 1=1
AND CURRENCY_CODE = 'INR'
AND CODE_COMBINATION_ID IN (SELECT CODE_COMBINATION_ID
FROM GL_JE_LINES
WHERE 1=1
AND JE_HEADER_ID = 3849823)
AND PERIOD_NAME = 'JAN-26'

----
SELECT *
FROM GL_IMPORT_REFERENCES                 --SUBLEDGER_DOC_SEQUENCE_ID : 3749 ,  SUBLEDGER_DOC_SEQUENCE_VALUE: 842625396
WHERE 1=1
AND REFERENCE_7 = '55939433'  -- THIS IS AE_HEADER_ID


--- 

SELECT *
FROM AP_BATCHES_ALL
WHERE 1=1
AND BATCH_ID IN (SELECT BATCH_ID FROM AP_INVOICES_ALL A
WHERE INVOICE_NUM = '1112AK')
ORDER BY CREATION_DATE DESC

/*
Payables A 587183 48179373
55939433 Purchase Invoices INR
*/

-- Creating Payment Terms : Payables -> Setup -> Invoices -> Payment Terms

SELECT *
FROM AP_TERMS
WHERE NAME = 'CLOUD_NET_10'

-- Creating Supplier and Sites : Payables -> Suppliers -> Entry
SELECT *
FROM AP_SUPPLIERS
WHERE 1=1
AND SEGMENT1 = '15172'
AND VENDOR_NAME = 'XX Custom Organization - Supplier'
AND VENDOR_ID = 461176


SELECT *
FROM AP_SUPPLIER_SITES_ALL
WHERE VENDOR_ID = 461176
