--- INVOICE --

SELECT 
  AIA.INVOICE_NUM
, AILA.LINE_NUMBER INV_LINE_NUM
, AIDA.DISTRIBUTION_LINE_NUMBER
, AIDA.ACCOUNTING_EVENT_ID  DIS_INV_EVENT_ID
, AIDA.AMOUNT DIST_AMT
, AIPA.ACCOUNTING_EVENT_ID  PAY_INV_EVENT_ID
, AIPA.AMOUNT PAYMENT_AMT
, ACA.BANK_ACCOUNT_NAME
, ACA.CHECK_NUMBER
, ACA.CURRENCY_CODE
FROM AP_INVOICES_ALL   AIA
, AP_INVOICE_LINES_ALL AILA
, AP_INVOICE_DISTRIBUTIONS_ALL AIDA
, AP_INVOICE_PAYMENTS_ALL AIPA
, AP_CHECKS_ALL ACA
WHERE 1=1
AND AIPA.CHECK_ID=ACA.CHECK_ID
AND AIA.INVOICE_ID = AIPA.INVOICE_ID
AND AILA.LINE_NUMBER = AIDA.INVOICE_LINE_NUMBER
AND AIA.INVOICE_ID = AIDA.INVOICE_ID
AND AIA.INVOICE_ID = AILA.INVOICE_ID
AND AIDA.DISTRIBUTION_LINE_NUMBER = NVL(:P_DISTRIBUTION_LINE_NUMBER, AIDA.DISTRIBUTION_LINE_NUMBER)
AND AILA.LINE_NUMBER = NVL(:P_LINE_NUM,AILA.LINE_NUMBER) 
AND AIA.INVOICE_ID = 1120838 --1120837 --1120838 --1120837 
ORDER BY 
  AIA.INVOICE_NUM
, AILA.LINE_NUMBER
, AIDA.DISTRIBUTION_LINE_NUMBER
, AIDA.ACCOUNTING_EVENT_ID  
, AIPA.ACCOUNTING_EVENT_ID  


-- GL Data --
SELECT 
  XLA_AEL.AE_LINE_NUM
, XLA_AEL.ACCOUNTING_CLASS_CODE
, XLA_AEL.GL_SL_LINK_ID
, XLA_AEL.ACCOUNTED_DR
, XLA_AEL.ACCOUNTED_CR
, GL_JE_H.JE_HEADER_ID
--, GL_JE_L.*
FROM
  XLA_EVENTS XLA_E
, XLA_AE_HEADERS XLA_AEH
, XLA_AE_LINES XLA_AEL
, GL_IMPORT_REFERENCES GL_IMP_REF
, GL_JE_BATCHES GL_JE_B
, GL_JE_HEADERS GL_JE_H
WHERE 1=1
AND GL_IMP_REF.JE_HEADER_ID = GL_JE_H.JE_HEADER_ID
AND GL_IMP_REF.JE_BATCH_ID = GL_JE_B.JE_BATCH_ID
AND XLA_AEL.GL_SL_LINK_ID = GL_IMP_REF.GL_SL_LINK_ID
AND XLA_AEH.AE_HEADER_ID = XLA_AEL.AE_HEADER_ID
AND XLA_E.ENTITY_ID = XLA_AEH.ENTITY_ID
AND XLA_AEH.EVENT_ID = 4561493 --- ACCOUNTING_EVENT_ID FROM AIDA -> AP_INVOICE_DISTRIBUTIONS_ALL ; IT IS NOT FROM  AIPA -> AP_INVOICE_PAYMENTS_ALL



---- GL_JE HEADERS AND LINES
SELECT GL_JE_L.*
FROM 
  GL_JE_HEADERS GL_JE_H
, GL_JE_LINES GL_JE_L
WHERE  1=1
AND GL_JE_H.JE_HEADER_ID = GL_JE_L.JE_HEADER_ID
AND GL_JE_H.JE_HEADER_ID = 3849829


-------------- COMPLETE -------------

SELECT DISTINCT 
  AIA.INVOICE_NUM
, AILA.LINE_NUMBER INV_LINE_NUM
, AIDA.DISTRIBUTION_LINE_NUMBER
, AIDA.ACCOUNTING_EVENT_ID  DIS_INV_EVENT_ID
, AIDA.AMOUNT DIST_AMT
, AIPA.ACCOUNTING_EVENT_ID  PAY_INV_EVENT_ID
, AIPA.AMOUNT PAYMENT_AMT
, ACA.BANK_ACCOUNT_NAME
, ACA.CHECK_NUMBER
, ACA.CURRENCY_CODE
, GL_JE_L.JE_LINE_NUM
, GL_JE_L.CODE_COMBINATION_ID
, GL_JE_L.ACCOUNTED_DR     
, GL_JE_L.ACCOUNTED_CR
FROM AP_INVOICES_ALL   AIA
, AP_INVOICE_LINES_ALL AILA
, AP_INVOICE_DISTRIBUTIONS_ALL AIDA
, AP_INVOICE_PAYMENTS_ALL AIPA
, AP_CHECKS_ALL ACA
, XLA_EVENTS XLA_E
, XLA_AE_HEADERS XLA_AEH
, XLA_AE_LINES XLA_AEL
, GL_IMPORT_REFERENCES GL_IMP_REF  
, GL_JE_BATCHES GL_JE_B
, GL_JE_HEADERS GL_JE_H 
, GL_JE_LINES GL_JE_L
WHERE 1=1
AND GL_JE_H.JE_HEADER_ID = GL_JE_L.JE_HEADER_ID
AND GL_IMP_REF.JE_HEADER_ID = GL_JE_H.JE_HEADER_ID
AND GL_IMP_REF.JE_BATCH_ID = GL_JE_B.JE_BATCH_ID
AND XLA_AEL.GL_SL_LINK_ID = GL_IMP_REF.GL_SL_LINK_ID 
AND XLA_AEH.AE_HEADER_ID = XLA_AEL.AE_HEADER_ID
AND XLA_E.ENTITY_ID = XLA_AEH.ENTITY_ID
AND AIDA.ACCOUNTING_EVENT_ID = XLA_E.EVENT_ID
AND AIPA.CHECK_ID=ACA.CHECK_ID
AND AIA.INVOICE_ID = AIPA.INVOICE_ID
AND AILA.LINE_NUMBER = AIDA.INVOICE_LINE_NUMBER
AND AIA.INVOICE_ID = AIDA.INVOICE_ID
AND AIA.INVOICE_ID = AILA.INVOICE_ID
AND AIDA.DISTRIBUTION_LINE_NUMBER = NVL(:P_DISTRIBUTION_LINE_NUMBER, AIDA.DISTRIBUTION_LINE_NUMBER)
AND AILA.LINE_NUMBER = NVL(:P_LINE_NUM,AILA.LINE_NUMBER) 
AND AIA.INVOICE_ID = 1120838 --1120837 --1120838 --1120837 
ORDER BY 
  AIA.INVOICE_NUM
, AILA.LINE_NUMBER
, GL_JE_L.JE_LINE_NUM
, AIDA.DISTRIBUTION_LINE_NUMBER
, AIDA.ACCOUNTING_EVENT_ID  
, AIPA.ACCOUNTING_EVENT_ID


------Perfect Query -> WITHOUT AP LINES AND AP DISTRIBUTIONS-------
SELECT GJH.NAME,
       GJL.JE_HEADER_ID,
       GJH.DESCRIPTION,
       TO_CHAR(GJH.DEFAULT_EFFECTIVE_DATE, 'dd-MON-yyyy') EFF_DATE,
       DECODE (XTE.ENTITY_CODE,
               'AP_INVOICES', PV.VENDOR_NAME,
               (SELECT AC.VENDOR_NAME
                  FROM AP_CHECKS_ALL AC
                 WHERE XTE.SOURCE_ID_INT_1 = AC.CHECK_ID)
       ) PARTY,
       AIA.INVOICE_NUM DOC_SEQUENCE_VALUE,
       GJH.JE_CATEGORY, 
       XAL.ACCOUNTING_CLASS_CODE,
       XAL.ACCOUNTED_DR ACCOUNTED_DR,
       XAL.ACCOUNTED_CR ACCOUNTED_CR,
       GJL.JE_HEADER_ID,
       XAL.PARTY_TYPE_CODE,
       GJH.JE_SOURCE,
       GJH.PERIOD_NAME,
       GCC.SEGMENT5,
       GJL.JE_LINE_NUM,
       GJH.DEFAULT_EFFECTIVE_DATE,
       AILA.LINE_NUMBER
  FROM GL_JE_BATCHES GJB,
       GL_JE_HEADERS GJH,
       GL_JE_LINES GJL,
       GL_CODE_COMBINATIONS GCC,
       GL_IMPORT_REFERENCES GIR,
       XLA_AE_LINES XAL,
       XLA_AE_HEADERS XAH,
       XLA.XLA_TRANSACTION_ENTITIES XTE,
       AP_INVOICES_ALL AIA,
       PO_VENDORS PV,
       AP_INVOICE_LINES_ALL AILA
 WHERE 1=1
   AND AIA.INVOICE_ID = AILA.INVOICE_ID
   AND GJB.JE_BATCH_ID = GJH.JE_BATCH_ID
   AND GJH.JE_HEADER_ID = GJL.JE_HEADER_ID
   AND GJL.CODE_COMBINATION_ID = GCC.CODE_COMBINATION_ID
   AND GJL.JE_HEADER_ID = GIR.JE_HEADER_ID
   AND GJL.JE_LINE_NUM = GIR.JE_LINE_NUM
   AND GIR.GL_SL_LINK_ID = XAL.GL_SL_LINK_ID
   AND GIR.GL_SL_LINK_TABLE = XAL.GL_SL_LINK_TABLE
   AND XAL.AE_HEADER_ID = XAH.AE_HEADER_ID
   AND XTE.APPLICATION_ID = XAH.APPLICATION_ID
   AND XTE.ENTITY_ID = XAH.ENTITY_ID
   AND AIA.INVOICE_ID(+) = XTE.SOURCE_ID_INT_1
   AND AIA.VENDOR_ID = PV.VENDOR_ID(+)
   AND GJL.STATUS = 'P'
   AND GCC.SEGMENT5 = NVL (:ACCOUNT_ID, GCC.SEGMENT5)
   AND TRUNC (GJH.DEFAULT_EFFECTIVE_DATE)
          BETWEEN NVL (:PERIOD_FROM, TRUNC (GJH.DEFAULT_EFFECTIVE_DATE))
              AND NVL (:PERIOD_TO, TRUNC (GJH.DEFAULT_EFFECTIVE_DATE))
   AND GJH.JE_SOURCE = 'Payables'
   AND AIA.INVOICE_ID =  1120838