--- Query for AP Invoice Headers Level Only

SELECT  ABA.BATCH_NAME INVOICE_BATCH,
        AIA.SOURCE INVOICE_SOURCE,
        AIA.ORG_ID,
        HOU.NAME OU_NAME,
        PCA.CHECKRUN_NAME,
        PCA.CHECK_DATE,
        PCA.CHECK_NUMBER DOCUMENT_NUMBER,
        (SELECT USER_NAME FROM FND_USER WHERE USER_ID = PCA.CREATED_BY) CHECKRUN_CREATEDBY,
        PCA.ATTRIBUTE5 VOID_RSN,
        PCA.ATTRIBUTE7 UTR_NO,
        PCA.ATTRIBUTE8 TXN_TYPE,
        PCA.BANK_ACCOUNT_NUM REMIT_TO,
        PCA.BANK_ACCOUNT_NAME,
        PCA.VOID_DATE,
        AIA.INVOICE_NUM,
        AIA.BATCH_ID,
        AIA.INVOICE_ID,
        AIA.DOC_SEQUENCE_VALUE VOUCHER_NUM,
        REPLACE(REPLACE(AIA.DESCRIPTION,CHR(10),''),CHR(13),'') DESCRIPTION,
        AIA.INVOICE_CURRENCY_CODE,
        AIA.PAYMENT_CURRENCY_CODE,
        AIA.INVOICE_DATE,
        AIA.INVOICE_AMOUNT,
        AIA.AMOUNT_PAID,
        AIA.GL_DATE,
        AIPA.PAYMENT_NUM,
        AIPA.AMOUNT PAYMENT_AMOUNT,
        AIPA.ACCOUNTING_DATE PAYMENT_DATE,
        REPLACE(REPLACE(ASI.VENDOR_NAME,CHR(10),''),CHR(13),'') VENDOR_NAME,
        REPLACE(REPLACE(ASI.VENDOR_NAME_ALT,CHR(10),''),CHR(13),'') VENDOR_NAME_ALT,
        ASI.SEGMENT1 VENDOR_NUMBER,
        AIA.PAY_GROUP_LOOKUP_CODE PAY_GROUP,
        REPLACE(REPLACE(ASSA.VENDOR_SITE_CODE,CHR(10),''),CHR(13),'') VENDOR_SITE_CODE,
        REPLACE(REPLACE(ASSA.VENDOR_SITE_CODE_ALT,CHR(10),''),CHR(13),'') VENDOR_SITE_CODE_ALT,
        FLV_VENDORTYPE.MEANING VENDOR_TYPE,
        FLV_INVOICETYPE.MEANING INVOICE_TYPE,
        FLV_PAYTYPE.MEANING PAYMENT_TYPE,
        FLV_PAYSTATUS.MEANING PAYMENT_STATUS,
        (SELECT GROSS_AMOUNT
                   FROM  AP_PAYMENT_SCHEDULES_ALL
                   WHERE INVOICE_ID  = AIA.INVOICE_ID
                   AND   PAYMENT_NUM = AIPA.PAYMENT_NUM
                   AND   ROWNUM=1) SCHEDULE_AMOUNT,
         (SELECT DUE_DATE
                   FROM  AP_PAYMENT_SCHEDULES_ALL
                   WHERE INVOICE_ID  = AIA.INVOICE_ID
                   AND   PAYMENT_NUM = AIPA.PAYMENT_NUM
                   AND   ROWNUM=1) DUE_DATE,
        AIA.ACCTS_PAY_CODE_COMBINATION_ID,
        DECODE(PCA.VOID_DATE,NULL,'NEGOTIABLE','VOID') INV_STATUS,
        PCA.CHECK_ID
FROM    AP_CHECKS_ALL PCA,
        AP_INVOICE_PAYMENTS_ALL AIPA,
        AP_INVOICES_ALL AIA,
        HR_OPERATING_UNITS HOU,
        AP_SUPPLIERS ASI,
        AP_SUPPLIER_SITES_ALL ASSA,
        AP_BATCHES_ALL ABA,
        FND_LOOKUP_VALUES FLV_VENDORTYPE,
        FND_LOOKUP_VALUES FLV_INVOICETYPE,
        FND_LOOKUP_VALUES FLV_PAYTYPE,
        FND_LOOKUP_VALUES FLV_PAYSTATUS
WHERE   1=1
AND     FLV_PAYSTATUS.LOOKUP_CODE       = AIA.PAYMENT_STATUS_FLAG
AND     FLV_PAYTYPE.LOOKUP_CODE         = PCA.PAYMENT_TYPE_FLAG
AND     FLV_INVOICETYPE.LOOKUP_CODE     = AIA.INVOICE_TYPE_LOOKUP_CODE
AND     FLV_VENDORTYPE.LOOKUP_CODE      = ASI.VENDOR_TYPE_LOOKUP_CODE
AND     ABA.BATCH_ID(+)                 = AIA.BATCH_ID
AND     ASSA.ORG_ID                     = AIPA.ORG_ID
AND     ASSA.VENDOR_SITE_ID             = AIA.VENDOR_SITE_ID
AND     ASI.VENDOR_ID                   = AIA.VENDOR_ID
AND     AIPA.ORG_ID                     = HOU.ORGANIZATION_ID
AND     HOU.SET_OF_BOOKS_ID             = AIPA.SET_OF_BOOKS_ID
AND     AIA.INVOICE_ID                  = AIPA.INVOICE_ID
AND     PCA.ORG_ID                      = AIPA.ORG_ID
AND     PCA.CHECK_ID                    = AIPA.CHECK_ID
AND     FLV_INVOICETYPE.LANGUAGE        = 'US'
AND     FLV_VENDORTYPE.LANGUAGE         = 'US'
AND     FLV_PAYTYPE.LANGUAGE            = 'US'
AND     FLV_PAYSTATUS.LANGUAGE          = 'US'
AND     NVL(FLV_PAYSTATUS.END_DATE_ACTIVE,SYSDATE+1) > SYSDATE
AND     NVL(FLV_INVOICETYPE.END_DATE_ACTIVE,SYSDATE+1) > SYSDATE
AND     NVL(FLV_VENDORTYPE.END_DATE_ACTIVE,SYSDATE+1) > SYSDATE
AND     NVL(FLV_PAYTYPE.END_DATE_ACTIVE,SYSDATE+1) > SYSDATE
AND     FLV_INVOICETYPE.LOOKUP_TYPE     = 'INVOICE TYPE'
AND     FLV_VENDORTYPE.LOOKUP_TYPE      = 'VENDOR TYPE'
AND     FLV_PAYTYPE.LOOKUP_TYPE         = 'PAYMENT TYPE'
AND     FLV_PAYSTATUS.LOOKUP_TYPE       = 'INVOICE PAYMENT STATUS'
--AND     AIPA.SET_OF_BOOKS_ID            = FND_PROFILE.VALUE('GL_SET_OF_BKS_ID')
--AND     TRUNC(NVL(AIPA.ACCOUNTING_DATE,SYSDATE))   BETWEEN NVL (TRUNC (TO_DATE (:P_TXNDATE_FROM,
--                                                                                'YYYY/MM/DD HH24:MI:SS')),
--                                                                TRUNC (NVL (AIPA.ACCOUNTING_DATE, SYSDATE)))
--                                                   AND NVL (:P_TXNDATE_TO,
--                                                                TRUNC (NVL (AIPA.ACCOUNTING_DATE, SYSDATE)))
--AND     ASI.VENDOR_ID                = NVL(:P_VENDOR_ID,ASI.VENDOR_ID)
--AND     AIA.ORG_ID                   = NVL(:P_OU_ID, AIA.ORG_ID)
--AND     ASI.VENDOR_TYPE_LOOKUP_CODE  = NVL(:P_VENDORTYPE, ASI.VENDOR_TYPE_LOOKUP_CODE)   
AND     AIA.INVOICE_ID = 1120837                                                         
ORDER BY INVOICE_NUM
        ,AIPA.PAYMENT_NUM
        ,ACCOUNTING_DATE;