SELECT  OOHA.ORDER_NUMBER
, OOHA.ORDER_TYPE_ID 
, OTTT.NAME ORDER_TYPE
, OTTT.DESCRIPTION ORDER_TYPE_DESCRIPTION
, OOHA.ORDERED_DATE 
, OOHA.REQUEST_DATE   
, OOHA.TRANSACTIONAL_CURR_CODE    
, OOHA.CUST_PO_NUMBER           
, OOHA.PAYMENT_TERM_ID
, RAT.NAME PAYMENT_TERM
, RAT.DESCRIPTION  PAYMENT_TERM_DESCRIPTION          
, OOHA.SOLD_FROM_ORG_ID           
, OOHA.SOLD_TO_ORG_ID            
, OOHA.SHIP_FROM_ORG_ID             
, OOHA.SHIP_TO_ORG_ID             
, OOHA.SHIP_FROM_ORG_ID              
, OOHA.INVOICE_TO_ORG_ID              
, OOHA.SALESREP_ID                 
, JRS.NAME  SALESREP
, OOHA.FLOW_STATUS_CODE                
, OOHA.BOOKED_DATE       
, RCTA.TRX_NUMBER
, RCTA.TRX_DATE 
--, RCTLA.LINE_NUMBER
--, RCTLA.INVENTORY_ITEM_ID
, RCTA.TERM_ID  
, RCTA.PRIMARY_SALESREP_ID
, RCTA.STATUS_TRX   
, ACRA.RECEIPT_NUMBER
, ACRA.CURRENCY_CODE
, ACRA.AMOUNT
, ACRA.PAY_FROM_CUSTOMER
, ACRA.STATUS
, ACRA.TYPE 
, RCTA.SOLD_TO_CUSTOMER_ID
, RCTA.BILL_TO_CUSTOMER_ID
, RCTA.BILL_TO_SITE_USE_ID
, RCTA.SHIP_TO_CUSTOMER_ID
, RCTA.SHIP_TO_SITE_USE_ID
, ACRA.RECEIPT_DATE
, ACRA.CONFIRMED_FLAG 
, ACRA.CUSTOMER_SITE_USE_ID 
, ARAA.APPLIED_CUSTOMER_TRX_ID
, ACRA.DEPOSIT_DATE        
, ACRA.RECEIPT_METHOD_ID       
, ACRA.OVERRIDE_REMIT_ACCOUNT_FLAG     
, ACRA.ORG_ID                
, ACRA.LEGAL_ENTITY_ID           
, CE_BAUA.BANK_ACCT_USE_ID
, CE_BAUA.BANK_ACCOUNT_ID
, CE_BAUA.AP_USE_ENABLE_FLAG
, CE_BAUA.AR_USE_ENABLE_FLAG
, CBBV.BANK_NAME
, CBBV.BANK_BRANCH_NAME
, CBBV.BANK_BRANCH_NAME_ALT
, CBBV.BRANCH_NUMBER
, CBBV.START_DATE
, CBBV.ADDRESS_LINE1
, CBBV.ADDRESS_LINE2
, CBBV.ADDRESS_LINE3
, CBBV.ADDRESS_LINE4
, CBBV.CITY
, CBBV.STATE
, CBBV.ZIP
, CBBV.COUNTRY
, CBBV.BANK_HOME_COUNTRY
, CBBV.BANK_INSTITUTION_TYPE
, CBBV.PK_ID
, CBBV.BRANCH_PARTY_ID
FROM CE_BANK_ACCT_USES_ALL CE_BAUA
, CE_BANK_ACCOUNTS CBA
, CE_BANK_BRANCHES_V CBBV
, AR_CASH_RECEIPTS_ALL ACRA
, AR_RECEIVABLE_APPLICATIONS_ALL ARAA
, RA_CUSTOMER_TRX_ALL RCTA
--, RA_CUSTOMER_TRX_LINES_ALL RCTLA
, OE_ORDER_HEADERS_ALL OOHA
, OE_TRANSACTION_TYPES_TL OTTT
, RA_TERMS RAT
, JTF_RS_SALESREPS JRS
WHERE 1=1
AND OOHA.SALESREP_ID = JRS.SALESREP_ID
AND OOHA.PAYMENT_TERM_ID = RAT.TERM_ID  
AND OOHA.ORDER_TYPE_ID = OTTT.TRANSACTION_TYPE_ID
AND RCTA.INTERFACE_HEADER_ATTRIBUTE1 = TO_CHAR(OOHA.ORDER_NUMBER)
AND RCTA.ORG_ID = OOHA.ORG_ID
--AND RCTA.CUSTOMER_TRX_ID = RCTLA.CUSTOMER_TRX_ID
--AND RCTLA.LINE_TYPE = 'LINE'
AND ARAA.APPLIED_CUSTOMER_TRX_ID = RCTA.CUSTOMER_TRX_ID
AND ACRA.CASH_RECEIPT_ID = ARAA.CASH_RECEIPT_ID
AND ARAA.DISPLAY = 'Y'
AND CBA.BANK_BRANCH_ID = CBBV.BRANCH_PARTY_ID
AND CE_BAUA.BANK_ACCOUNT_ID = CBA.BANK_ACCOUNT_ID
AND CE_BAUA.BANK_ACCT_USE_ID = ACRA.REMIT_BANK_ACCT_USE_ID 
AND RCTA.CUSTOMER_TRX_ID = 13570