DECLARE
   L_RETURN_STATUS VARCHAR2(1);
   L_MSG_COUNT NUMBER;
   L_MSG_DATA VARCHAR2(240);
   L_CASH_RECEIPT_ID NUMBER;
   P_COUNT NUMBER := 0;
BEGIN
    -- 1) SET THE APPLICATIONS CONTEXT
    MO_GLOBAL.INIT('AR');
    MO_GLOBAL.SET_POLICY_CONTEXT('S','82');

   AR_RECEIPT_API_PUB.UNAPPLY_ON_ACCOUNT
   ( P_API_VERSION => 1.0,
     P_INIT_MSG_LIST => FND_API.G_TRUE,
     P_COMMIT => FND_API.G_TRUE,
     P_VALIDATION_LEVEL => FND_API.G_VALID_LEVEL_FULL,
     X_RETURN_STATUS => L_RETURN_STATUS,
     X_MSG_COUNT => L_MSG_COUNT,
     X_MSG_DATA => L_MSG_DATA,
     P_CASH_RECEIPT_ID => 463622,
     P_REVERSAL_GL_DATE => TRUNC(SYSDATE));

    -- 3) REVIEW THE API OUTPUT
    DBMS_OUTPUT.PUT_LINE('STATUS : ' || L_RETURN_STATUS);
    DBMS_OUTPUT.PUT_LINE('MESSAGE COUNT : ' || L_MSG_COUNT);

    IF L_MSG_COUNT = 1 THEN
       DBMS_OUTPUT.PUT_LINE('L_MSG_DATA : '|| L_MSG_DATA);
    ELSIF L_MSG_COUNT > 1 THEN
       LOOP
          P_COUNT := P_COUNT + 1;
          L_MSG_DATA := FND_MSG_PUB.GET(FND_MSG_PUB.G_NEXT,FND_API.G_FALSE);
          IF L_MSG_DATA IS NULL THEN
             EXIT;
          END IF;
          DBMS_OUTPUT.PUT_LINE('MESSAGE : ' || P_COUNT ||'. '||L_MSG_DATA);
       END LOOP;
    END IF; 
    DBMS_OUTPUT.PUT_LINE('MESSAGE EXIT.');
END AR_UNAPPLY_ON_ACCT_RECEIPT;