-- Vendor and Their Bank Account's Detail
SELECT  APS.VENDOR_NAME "VERDOR NAME",
        APSS.VENDOR_SITE_CODE "VENDOR SITE CODE",
        IEB.BANK_NAME "BANK NAME",
        IEBB.BANK_BRANCH_NAME "BANK BRANCH NAME",
        IEBB.BRANCH_NUMBER "BRANCH NUMBER",
        IEBA.BANK_ACCOUNT_NUM "BANK ACCOUNT NUMBER",
        IEBA.BANK_ACCOUNT_NAME "BANK ACCOUNT NAME"
FROM    AP.AP_SUPPLIERS APS,
        AP.AP_SUPPLIER_SITES_ALL ASSA,
        APPS.IBY_EXT_BANK_ACCOUNTS IBY_EBA,
        APPS.IBY_ACCOUNT_OWNERS IBY_AO,
        APPS.IBY_EXT_BANKS_V IBY_EBV,
        APPS.IBY_EXT_BANK_BRANCHES_V IBY_EBBV
WHERE   APS.VENDOR_ID = ASSA.VENDOR_ID
        AND IBY_AO.ACCOUNT_OWNER_PARTY_ID = APS.PARTY_ID
        AND IBY_EBA.EXT_BANK_ACCOUNT_ID = IBY_AO.EXT_BANK_ACCOUNT_ID
        AND IBY_EBA.BRANCH_ID = IBY_EBBV.BRANCH_PARTY_ID
        AND IBY_EBA.BANK_ID = IBY_EBV.BANK_PARTY_ID
        AND IBY_EBV.BANK_PARTY_ID = IBY_EBBV.BANK_PARTY_ID
		AND APS.VENDOR_NAME = 'XX Custom Organization - Supplier';
		
-- Branch Name and Branch Number : IBY_EXT_BANK_BRANCHES_V
SELECT CEBRANCH.BRANCH_PARTY_ID BRANCH_PARTY_ID,
	  CEBRANCH.COUNTRY HOME_COUNTRY,
	  CEBRANCH.BANK_BRANCH_NAME BANK_BRANCH_NAME,
	  CEBRANCH.BANK_BRANCH_NAME_ALT BANK_BRANCH_NAME_ALT,
	  CEBRANCH.BRANCH_NUMBER BRANCH_NUMBER,
	  CEBRANCH.START_DATE START_DATE, CEBRANCH.END_DATE END_DATE,
	  CEBRANCH.ADDRESS_LINE1 ADDRESS_LINE1,
	  CEBRANCH.ADDRESS_LINE2 ADDRESS_LINE2,
	  CEBRANCH.ADDRESS_LINE3 ADDRESS_LINE3,
	  CEBRANCH.ADDRESS_LINE4 ADDRESS_LINE4, CEBRANCH.CITY CITY,
	  CEBRANCH.STATE STATE, CEBRANCH.PROVINCE PROVINCE, CEBRANCH.ZIP ZIP,
	  CEBRANCH.COUNTRY COUNTRY,
	  CEBRANCH.BANK_BRANCH_TYPE BANK_BRANCH_TYPE,
	  CEBRANCH.DESCRIPTION DESCRIPTION,
	  CEBRANCH.EFT_SWIFT_CODE EFT_SWIFT_CODE,
	  CEBRANCH.EFT_USER_NUMBER EFT_USER_NUMBER,
	  CEBRANCH.BANK_PARTY_ID BANK_PARTY_ID,
	  1 CREATED_BY,
	  SYSDATE CREATION_DATE, 1 LAST_UPDATED_BY, SYSDATE LAST_UPDATE_DATE,
	  1 LAST_UPDATE_LOGIN, 1 OBJECT_VERSION_NUMBER, 'Y' OPERATION_FLAG
 FROM CE_BANK_BRANCHES_V CEBRANCH;
COMMENT ON TABLE APPS.IBY_EXT_BANK_BRANCHES_V IS '<h5 Class="errorText">***** Warning: Oracle Internal Use Only *****</h5><p> <b class="errorText">Oracle Corporation does not support access to Oracle
applications data using this object, except from standard Oracle Applications  programs.</b></p><h5>View Type</h5><p>Internal</p>';

