-- WORKING SEGMENT FOR CHART_OF_ACCOUNTS_ID AND SET_OF_BOOKS_ID ACCORDING TO INVENTORY ORGANIZATION

/* Formatted on 4/8/2026 11:16:37 AM (QP5 v5.365) */
  SELECT ID_FLEX_STRUCTURE_CODE
	, CONCATENATED_SEGMENT_DELIMITER 
	, ID_FLEX_STRUCTURE_NAME
	, DESCRIPTION
	, STRUCTURE_VIEW_NAME
	, FREEZE_FLEX_DEFINITION_FLAG
	, ENABLED_FLAG
	, CONCATENATED_SEGMENT_DELIMITER
	, CROSS_SEGMENT_VALIDATION_FLAG
	, FREEZE_STRUCTURED_HIER_FLAG
	, DYNAMIC_INSERTS_ALLOWED_FLAG
	, SHORTHAND_ENABLED_FLAG
	, SHORTHAND_PROMPT
	, SHORTHAND_LENGTH
	, APPLICATION_ID
	, ID_FLEX_CODE
	, ID_FLEX_NUM
	, LAST_UPDATE_DATE
	, LAST_UPDATED_BY
	, CREATION_DATE
	, CREATED_BY
	, LAST_UPDATE_LOGIN
	, ROW_ID
    FROM FND_ID_FLEX_STRUCTURES_VL
   WHERE (APPLICATION_ID = 101) AND (ID_FLEX_CODE = 'GL#')
   AND ID_FLEX_NUM = (SELECT CHART_OF_ACCOUNTS_ID 
                            FROM ORG_ORGANIZATION_DEFINITIONS
                            WHERE ORGANIZATION_ID = 274 
                            AND SET_OF_BOOKS_ID = fnd_profile.value('GL_SET_OF_BKS_ID')
                            AND OPERATING_UNIT = 288
                     )
    AND ENABLED_FLAG = 'Y'
    AND DYNAMIC_INSERTS_ALLOWED_FLAG = 'Y'
ORDER BY application_id, id_flex_code, id_flex_structure_name